<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

class OmniController extends Controller
{
    public function index()
    {
        return response()->json(['message' => 'Generated by Crom-Omni']);
    }
}
