// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
    print_opt(msg, true);
}
function to_string(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_f(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_b(b) {
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}
// ===== END: std/core.omni =====

function header(text) {
    print("╔══════════════════════════════════════╗");
    print("║   " + text);
    print("╚══════════════════════════════════════╝");
}
function factorial(n) {
    if (n <= 1) {
            return 1;
    }
    return n * factorial(n - 1);
}
function fibonacci(n) {
    if (n <= 1) {
            return n;
    }
    return fibonacci(n - 1) + fibonacci(n - 2);
}
function classify(n) {
    if (n < 0) {
            return "negative";
    }
    if (n === 0) {
            return "zero";
    }
    return "positive";
}
function main() {
    header("OMNI - Flow Control");
    print("");
    print("1. Factorial (recursion):");
    print("   5! = " + to_string(factorial(5)));
    print("   10! = " + to_string(factorial(10)));
    print("");
    print("2. Fibonacci (recursion):");
    print("   fib(10) = " + to_string(fibonacci(10)));
    print("   fib(15) = " + to_string(fibonacci(15)));
    print("");
    print("3. Classification:");
    print("   -5 is " + classify(0 - 5));
    print("   0 is " + classify(0));
    print("   10 is " + classify(10));
    print("");
    print("✓ Pure Omni logic - works on all modes!");
}

if (typeof main === 'function') main();
