// Generated by Omni Compiler
'use strict';

function log(msg) {{
     console.log(msg); 

}}
function header(text) {{
        log("╔══════════════════════════════════════╗");
        log("║   " + text);
        log("╚══════════════════════════════════════╝");
}}
function is_negative(n) {{
                if (n < 0) {{
                                return true;
                }}
                return false;
}}
function is_zero(n) {{
                        if (n === 0) {{
                                                return true;
                        }}
                        return false;
}}
function factorial(n) {{
                                if (n <= 1) {{
                                                                return 1;
                                }}
                                return n * factorial(n - 1);
}}
function fibonacci(n) {{
                                        if (n <= 1) {{
                                                                                return n;
                                        }}
                                        return fibonacci(n - 1) + fibonacci(n - 2);
}}
function main() {{
                                            header("OMNI - Flow Control");
                                            log("");
                                            log("1. Conditionals:");
                                                if (is_negative(0 - 5)) {{
                                                                                                log("   -5 is negative");
                                                }}
                                                    if (is_zero(0)) {{
                                                                                                        log("   0 is zero");
                                                    }}
                                                        if (is_negative(10) === false) {{
                                                                                                                log("   10 is positive");
                                                        }}
                                                        log("");
                                                        log("2. Recursion - Factorial:");
                                                        log("   5! = " + factorial(5));
                                                        log("   10! = " + factorial(10));
                                                        log("");
                                                        log("3. Recursion - Fibonacci:");
                                                        log("   fib(10) = " + fibonacci(10));
                                                        log("   fib(15) = " + fibonacci(15));
                                                        log("");
                                                        log("✓ Pure Omni logic - 100% portable!");
}}

if (typeof main === 'function') main();
