// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function is_negative(n) {{
            if (n < 0) {{
                        return true;
            }}
            return false;
}}
function is_zero(n) {{
                    if (n === 0) {{
                                        return true;
                    }}
                    return false;
}}
function factorial(n) {{
                            if (n <= 1) {{
                                                        return 1;
                            }}
                            return n * factorial(n - 1);
}}
function main() {{
                                print("╔══════════════════════════════════════╗");
                                print("║   OMNI - Flow Control                ║");
                                print("╚══════════════════════════════════════╝");
                                print("");
                                print("1. if/else - Number Classification:");
                                    if (is_negative(0 - 5)) {{
                                                                        print("   -5 is negative");
                                    }}
                                        if (is_zero(0)) {{
                                                                                print("   0 is zero");
                                        }}
                                            if (is_negative(10) === false) {{
                                                                                        print("   10 is positive");
                                            }}
                                            print("");
                                            print("2. Recursion - Factorial:");
                                            let f5 = factorial(5);
                                            let f10 = factorial(10);
                                            print("   5! = " + f5);
                                            print("   10! = " + f10);
                                            print("");
                                            print("✓ Pure Omni flow control!");
}}

if (typeof main === 'function') main();
