// Generated by Omni Compiler
'use strict';

function print(msg) {
     console.log(msg); 

}
function Entity_create(name) {
        console.log("   [ENTITY] " + name + " { id, fields... }");
}
function Server_route(method, path) {
            console.log("   [" + method + "] " + path);
}
function UI_component(name) {
                console.log("   [UI] <" + name + " />");
}
function main() {
                    console.log("╔══════════════════════════════════════╗");
                    console.log("║   OMNI - Adapters Showcase           ║");
                    console.log("╚══════════════════════════════════════╝");
                    console.log("");
                    console.log("Adapter decorators compile to any framework!");
                    console.log("");
                    console.log("1. @entity - Data Models:");
                    Entity_create("User");
                    Entity_create("Product");
                    console.log("");
                    console.log("2. @server - API Routes:");
                    Server_route("GET", "/api/users");
                    Server_route("POST", "/api/users");
                    Server_route("DELETE", "/api/users/:id");
                    console.log("");
                    console.log("3. @ui - Components:");
                    UI_component("Dashboard");
                    UI_component("UserList");
                    UI_component("Button");
                    console.log("");
                    console.log("Target Framework Mapping:");
                    console.log("   @entity   -> Prisma / Eloquent / SQLAlchemy");
                    console.log("   @server   -> Express / FastAPI / Laravel");
                    console.log("   @ui       -> React / Vue / Svelte");
                    console.log("");
                    console.log("✓ Same code compiles to different frameworks!");
}

module.exports = { print, Entity_create, Server_route, UI_component, main };

if (typeof main === 'function') { main(); }
