// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function Entity_create(name) {{
        print("   [ENTITY] " + name + " { id, fields... }");
}}
function Server_route(method, path) {{
            print("   [" + method + "] " + path);
}}
function UI_component(name) {{
                print("   [UI] <" + name + " />");
}}
function main() {{
                    print("╔══════════════════════════════════════╗");
                    print("║   OMNI - Adapters Showcase           ║");
                    print("╚══════════════════════════════════════╝");
                    print("");
                    print("Adapter decorators compile to any framework!");
                    print("");
                    print("1. @entity - Data Models:");
                    Entity_create("User");
                    Entity_create("Product");
                    print("");
                    print("2. @server - API Routes:");
                    Server_route("GET", "/api/users");
                    Server_route("POST", "/api/users");
                    Server_route("DELETE", "/api/users/:id");
                    print("");
                    print("3. @ui - Components:");
                    UI_component("Dashboard");
                    UI_component("UserList");
                    UI_component("Button");
                    print("");
                    print("Target Framework Mapping:");
                    print("   @entity   -> Prisma / Eloquent / SQLAlchemy");
                    print("   @server   -> Express / FastAPI / Laravel");
                    print("   @ui       -> React / Vue / Svelte");
                    print("");
                    print("✓ Same code compiles to different frameworks!");
}}

if (typeof main === 'function') main();
