// Generated by Omni Compiler
'use strict';


function print(msg) {
console.log(msg);

}

// Capsule: Test
const Test = {};

Test.main = function() {
const s = `Line 1
            Line '2'`;
            console.log(s);
}
;


