# Generated by Omni Compiler
import sys

from core_omni import *
from ui_omni import *

input_ref = TextInput(handle=0, id="")

list_y = 120

main_win = Window(handle=0, id="")

def add_todo():
    global list_y
    text = TextInput_get_value(input_ref)
    if text:
        print(("Adding Task: " + text))
        Label_create(main_win, ("- " + text), 20, list_y)
        list_y = (list_y + 30)

def main():
    global input_ref, main_win
    print("Starting Universal Todo App...")
    config = WindowConfig(title="Omni Universal Todo", width=400, height=600, background="#ffffff")
    main_win = Window_create(config)
    Label_create(main_win, "Universal Todo List", 20, 20)
    input_ref = TextInput_create(main_win, 20, 60, 250)
    btn = Button_create(main_win, "Add Task", 280, 58)
    Button_on_click(btn, add_todo)
    UI_run()


if __name__ == "__main__":
    main()

