# Generated by Omni Compiler
import sys

import core_omni

ui_root_ref = 0

class WindowConfig:
    def __init__(self, **data):
        if data is None: data = {}
        self.title = data.get('title')
        self.width = data.get('width')
        self.height = data.get('height')
        self.background = data.get('background')

class Window:
    def __init__(self, **data):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.id = data.get('id')

class Button:
    def __init__(self, **data):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.id = data.get('id')
        self.text = data.get('text')

class Label:
    def __init__(self, **data):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.id = data.get('id')
        self.text = data.get('text')

class TextInput:
    def __init__(self, **data):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.id = data.get('id')

def Window_create(config):
    win = Window(handle=0, id="main")
    # native "js" block not supported
    import tkinter as tk
    global ui_root_ref
    if ui_root_ref == 0 or ui_root_ref is None:
        ui_root_ref = tk.Tk()
        
    ui_root_ref.title(config.title)
    ui_root_ref.geometry(f"{config.width}x{config.height}")
    if config.background:
        ui_root_ref.configure(bg=config.background)
            
    win.handle = ui_root_ref
    return win

def Button_create(win, text, x, y):
    btn = Button(handle=0, id=("btn_" + text), text=text)
    # native "js" block not supported
    import tkinter as tk
    from tkinter import ttk
    b = ttk.Button(ui_root_ref, text=text)
    b.place(x=x, y=y)
    btn.handle = b
    return btn

def Button_on_click(btn, callback):
    # native "js" block not supported
    def wrapper():
            callback()
    btn.handle.config(command=wrapper)

def Label_create(win, text, x, y):
    lbl = Label(handle=0, id="lbl", text=text)
    # native "js" block not supported
    import tkinter as tk
    bg = ui_root_ref.cget('bg')
    l = tk.Label(ui_root_ref, text=text, bg=bg)
    l.place(x=x, y=y)
    lbl.handle = l
    return lbl

def Label_set_text(lbl, text):
    # native "js" block not supported
    lbl.handle.config(text=text)

def TextInput_create(win, x, y, width):
    input = TextInput(handle=0, id="input")
    # native "js" block not supported
    import tkinter as tk
    from tkinter import ttk
    i = ttk.Entry(ui_root_ref)
    i.place(x=x, y=y, width=width)
    input.handle = i
    return input

def TextInput_get_value(input):
    val = ""
    # native "js" block not supported
    val = input.handle.get()
    return val

def UI_run():
    # native "js" block not supported
    # global ui_root
    if ui_root_ref:
        ui_root_ref.mainloop()


