// Generated by Omni Compiler
'use strict';


class User {
    constructor(data = {}) {
        this.id = data.id;
        this.name = data.name;
        this.roles = data.roles;
    }
}
User.__attributes = [{ name: 'entity', args: [] }];

// Capsule: AuthSystem
const AuthSystem = {};

AuthSystem.validate_access = function(user) {
    let has_role = false;
    for (const role of user.roles) {
    if (role === "admin") {
    has_role = true;
}

}

    return has_role;
}
;
AuthSystem.login = function(name) {
    let u = new User({ id: 1, name: name, roles: ["user", "admin"] });
    let allowed = AuthSystem.validate_access(u);
console.log(`User ${name} allowed: ${allowed}`);
}
;


function main() {
    AuthSystem.login("AdminUser");
}


// Entry Point
if (require.main === module) {
    main();
}

