// Generated by Omni Compiler
'use strict';


function print(msg) {
console.log(msg);

}

class User {
    constructor(data = {}) {
        this.id = data.id;
        this.name = data.name;
        this.email = data.email;
    }
}

function saveUser(name, email) {
    print("Saving user: " + name);
    return true;
}

function listUsers() {
    print("User 1: Alice (alice@example.com)");
    print("User 2: Bob (bob@example.com)");
}

function deleteUser(id) {
    print("Deleting user with id: " + to_string(id));
    return true;
}

function main() {
    print("=== Universal CRUD Demo ===");
    listUsers();
    saveUser("Charlie", "charlie@example.com");
    deleteUser(1);
    print("=== Demo Complete ===");
}


// Auto-Main Invocation (Phase 6 Parity)
if (typeof main === 'function') {
    main();
}
