# Generated by Omni Compiler
import sys

def omni_print(val):
    if val is True: print('true')
    elif val is False: print('false')
    else: print(val)

def to_string(val):
    return str(val)



class User:
    def __init__(self, data=None):
        if data is None: data = {}
        self.id = data.get('id')
        self.name = data.get('name')
        self.email = data.get('email')

def saveUser(name, email):
    omni_print(("Saving user: " + name))
    return True

def listUsers():
    omni_print("User 1: Alice (alice@example.com)")
    omni_print("User 2: Bob (bob@example.com)")

def deleteUser(id):
    omni_print(("Deleting user with id: " + to_string(id)))
    return True

def main():
    omni_print("=== Universal CRUD Demo ===")
    listUsers()
    saveUser("Charlie", "charlie@example.com")
    deleteUser(1)
    omni_print("=== Demo Complete ===")


if __name__ == "__main__":
    main()
