use anyhow::Result;
use std::path::PathBuf;
use crate::core::config::OmniConfig;

pub trait FrameworkAdapter {
    fn name(&self) -> &str;
    fn scaffold(&self, output_dir: &PathBuf, config: &OmniConfig) -> Result<()>;
}

pub struct LaravelAdapter;

impl FrameworkAdapter for LaravelAdapter {
    fn name(&self) -> &str {
        "laravel"
    }

    fn scaffold(&self, output_dir: &PathBuf, config: &OmniConfig) -> Result<()> {
        println!("   🐘 Scaffolding Laravel Project: {}", config.project.name);
        
        // Example scaffolding logic
        let app_dir = output_dir.join("app");
        std::fs::create_dir_all(&app_dir)?;
        
        // Create basic routes
        let routes_file = output_dir.join("routes/web.php");
        if let Some(parent) = routes_file.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(routes_file, "<?php\n\nuse Illuminate\\Support\\Facades\\Route;\n\nRoute::get('/', function () {\n    return view('welcome');\n});\n")?;

        // Create standard Controller
        let controller_path = output_dir.join("app/Http/Controllers/OmniController.php");
        if let Some(parent) = controller_path.parent() {
             std::fs::create_dir_all(parent)?;
        }
        std::fs::write(controller_path, r#"<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

class OmniController extends Controller
{
    public function index()
    {
        return response()->json(['message' => 'Generated by Crom-Omni']);
    }
}
"#)?;

        // Create virtual migration based on config name
        let migration_name = format!("database/migrations/2024_01_01_000000_create_{}_table.php", config.project.name.to_lowercase());
        let migration_path = output_dir.join(migration_name);
        if let Some(parent) = migration_path.parent() {
             std::fs::create_dir_all(parent)?;
        }
        std::fs::write(migration_path, format!(r#"<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{{
    public function up(): void
    {{
        Schema::create('{}', function (Blueprint $table) {{
            $table->id();
            $table->string('name');
            $table->timestamps();
        }});
    }}

    public function down(): void
    {{
        Schema::dropIfExists('{}');
    }}
}};
"#, config.project.name.to_lowercase(), config.project.name.to_lowercase()))?;
        
        println!("   ✅ Laravel structure created at {}", output_dir.display());
        Ok(())
    }
}
