// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
    print_opt(msg, true);
}
function to_string(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_f(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_b(b) {
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/http.omni =====
class HttpResponse {
    constructor(data = {}) {
        this.status = data.status;
        this.body = data.body;
        this.ok = data.ok;
    }

}
function http_get(url) {
    let response = new HttpResponse({ status: 0, body: "", ok: false });
    
            // Simulated for demo - real implementation would use fetch/http
            response.status = 200;
            response.body = '{"status": "ok", "source": "omni-http"}';
            response.ok = true;
            console.log("[HTTP] GET " + url);
        

    return response;
}
function http_post(url, data) {
    let response = new HttpResponse({ status: 0, body: "", ok: false });
    
            response.status = 201;
            response.body = '{"created": true}';
            response.ok = true;
            console.log("[HTTP] POST " + url);
        

    return response;
}
// ===== END: std/http.omni =====

function header(text) {
    print("╔══════════════════════════════════════╗");
    print("║   " + text);
    print("╚══════════════════════════════════════╝");
}
function main() {
    header("OMNI - HTTP API Client");
    print("");
    print("1. GET Request:");
    let res1 = http_get("https://api.example.com/users");
    print("   Status: " + to_string(res1.status));
    print("   Response: " + res1.body);
    print("");
    print("2. POST Request:");
    let res2 = http_post("https://api.example.com/users", "data");
    print("   Status: " + to_string(res2.status));
    print("   Response: " + res2.body);
    print("");
    print("✓ Same API works on --cmd, --web, --app!");
}

if (typeof main === 'function') main();
