// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function http_get_demo(url) {{
        let response = "";
        
                response = '{"status": "ok", "source": "omni-http"}';
                console.log("[HTTP] GET " + url);
            

        return response;
}}
function main() {{
            print("╔══════════════════════════════════════╗");
            print("║   OMNI - HTTP API Client             ║");
            print("╚══════════════════════════════════════╝");
            print("");
            print("1. Making HTTP GET Request:");
            let response = http_get_demo("https://api.example.com/data");
            print("   Response: " + response);
            print("");
            print("2. Response contains:");
            print("   status: ok");
            print("   source: omni-http");
            print("");
            print("✓ HTTP API client example completed!");
}}

if (typeof main === 'function') main();
