// Generated by Omni Compiler
'use strict';

function log(msg) {{
     console.log(msg); 

}}
function header(text) {{
        log("╔══════════════════════════════════════╗");
        log("║   " + text);
        log("╚══════════════════════════════════════╝");
}}
function http_get(url) {{
            let response = "";
            
                    response = '{"status": "ok", "data": "from JS"}';
                    console.log("[HTTP] GET " + url);
                

            return response;
}}
function http_post(url, body) {{
                let response = "";
                
                        response = '{"status": "created", "id": 123}';
                        console.log("[HTTP] POST " + url);
                    

                return response;
}}
function main() {{
                    header("OMNI - HTTP API Client");
                    log("");
                    log("1. GET Request:");
                    let get_result = http_get("https://api.example.com/users");
                    log("   Response: " + get_result);
                    log("");
                    log("2. POST Request:");
                    let post_result = http_post("https://api.example.com/users", "data");
                    log("   Response: " + post_result);
                    log("");
                    log("✓ Same API works on --cmd, --web, --app!");
}}

if (typeof main === 'function') main();
