# Generated by Omni Compiler
import sys
import codecs
try:
    if sys.stdout.encoding != 'utf-8':
        sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

class Console:
    def log(self, *args): print(*args)
    def error(self, *args): print("ERROR:", *args)

console = Console()

def print(msg):

    sys.stdout.write(str(msg) + '\n') 

def get(x): pass
def post(x): pass
def delete(x): pass
def screen(x): pass

class Task:
    def __init__(self, data={}):
        self.id = data.get('id')
        self.title = data.get('title')
        self.completed = data.get('completed')

tasks = []
next_id = 1
get("/api/tasks")
def api_get_tasks():
    print("[API] GET /api/tasks - Returning " + tasks.length + " tasks")
post("/api/tasks")
def api_create_task(title):
    print("[API] POST /api/tasks - Creating: " + title)
delete("/api/tasks/:id")
def api_delete_task(id):
    print("[API] DELETE /api/tasks/" + id)
screen("TaskManager")
class TaskManager:
    @staticmethod
    def render():
        print("[UI] Rendering Task Manager screen")

def create_web_ui():


    import tkinter as tk
    from tkinter import messagebox

    def on_add():
         val = entry.get()
         if val:
             listbox.insert(tk.END, val)
             entry.delete(0, tk.END)
             print("[API] POST /api/tasks - Created task: " + val)

    def on_delete():
         sel = listbox.curselection()
         if sel:
             val = listbox.get(sel[0])
             listbox.delete(sel[0])
             print("[API] DELETE /api/tasks - " + val)

    root = tk.Tk()
    root.title("OMNI Task Manager (Native)")
    root.geometry("400x500")

    lbl = tk.Label(root, text="Omni Task Manager", font=("Arial", 16))
    lbl.pack(pady=10)

    frame = tk.Frame(root)
    frame.pack(pady=10)

    entry = tk.Entry(frame, width=30)
    entry.pack(side=tk.LEFT, padx=5)

    btn = tk.Button(frame, text="Add", command=on_add)
    btn.pack(side=tk.LEFT)

    listbox = tk.Listbox(root, width=50, height=15)
    listbox.pack(pady=10, padx=10)

    btn_del = tk.Button(root, text="Delete Selected", command=on_delete)
    btn_del.pack(pady=5)

    lbl_info = tk.Label(root, text="@entity Task | @server API | @ui Desktop", fg="gray")
    lbl_info.pack(side=tk.BOTTOM, pady=10)

    root.mainloop()

def main():
    print("╔══════════════════════════════════════╗")
    print("║   OMNI - Fullstack Task Manager      ║")
    print("╚══════════════════════════════════════╝")
    print("")
    print("Layers:")
    print("  @entity Task { id, title, completed }")
    print("  @server GET/POST/DELETE /api/tasks")
    print("  @ui.screen TaskManager")
    print("")
    create_web_ui()
    print("✓ Fullstack app running!")

__all__ = ["print", "api_get_tasks", "api_create_task", "api_delete_task", "create_web_ui", "main"]

if __name__ == '__main__':
    if 'main' in globals():
        main()
