// Generated by Omni Compiler
'use strict';

function print(msg) {
    console.log(msg); 

}

function get() {}
function post() {}
function screen() {}

class Task {
    constructor(data = {}) {
        this.id = data.id;
        this.title = data.title;
        this.completed = data.completed;
    }

}
let tasks = [];
let next_id = 1;
get("/api/tasks");
function api_get_tasks() {
        console.log("[API] GET /api/tasks - Returning " + tasks.length + " tasks");
}
post("/api/tasks");
function api_create_task(title) {
            console.log("[API] POST /api/tasks - Creating: " + title);
}
delete("/api/tasks/:id");
function api_delete_task(id) {
                console.log("[API] DELETE /api/tasks/" + id);
}
screen("TaskManager");
// Capsule: TaskManager
const TaskManager = {
    render() {
                    console.log("[UI] Rendering Task Manager screen");    },

};

function create_web_ui() {

                    let tasks = [];
                    let nextId = 1;

                    document.body.innerHTML = `
                        <div style="max-width: 600px; margin: 40px auto; font-family: system-ui;">
                            <h1 style="color: #333; text-align: center;">📋 Omni Task Manager</h1>
                            <p style="text-align: center; color: #666;">Fullstack app: @entity + @server + @ui</p>

                            <div style="display: flex; gap: 10px; margin: 20px 0;">
                                <input id="taskInput" type="text" placeholder="Enter new task..." 
                                    style="flex: 1; padding: 12px; border: 2px solid #ddd; border-radius: 8px; font-size: 16px;">
                                <button onclick="addTask()" 
                                    style="padding: 12px 24px; background: linear-gradient(135deg, #667eea, #764ba2); color: white; border: none; border-radius: 8px; cursor: pointer; font-size: 16px;">
                                    Add
                                </button>
                            </div>

                            <div id="taskList"></div>

                            <div style="margin-top: 30px; padding: 20px; background: #f5f5f5; border-radius: 8px;">
                                <h3>🔧 Architecture Layers</h3>
                                <p><strong>@entity Task</strong> - Data model with id, title, completed</p>
                                <p><strong>@server.get/post/delete</strong> - API routes</p>
                                <p><strong>@ui.screen</strong> - This UI you're seeing</p>
                            </div>
                        </div>
                    `;

                    window.addTask = function() {
                        const input = document.getElementById('taskInput');
                        if (input.value.trim()) {
                            tasks.push({ id: nextId++, title: input.value, completed: false });
                            input.value = '';
                            renderTasks();
                            console.log("[API] POST /api/tasks - Created task");
                        }
                    };

                    window.toggleTask = function(id) {
                        const task = tasks.find(t => t.id === id);
                        if (task) {
                            task.completed = !task.completed;
                            renderTasks();
                        }
                    };

                    window.deleteTask = function(id) {
                        tasks = tasks.filter(t => t.id !== id);
                        renderTasks();
                        console.log("[API] DELETE /api/tasks/" + id);
                    };

                    function renderTasks() {
                        const list = document.getElementById('taskList');
                        if (tasks.length === 0) {
                            list.innerHTML = '<p style="text-align: center; color: #999;">No tasks yet. Add one above!</p>';
                            return;
                        }

                        list.innerHTML = tasks.map(t => `
                            <div style="display: flex; align-items: center; gap: 10px; padding: 15px; margin: 10px 0; background: ${t.completed ? '#e8f5e9' : 'white'}; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
                                <input type="checkbox" ${t.completed ? 'checked' : ''} onchange="toggleTask(${t.id})" style="width: 20px; height: 20px;">
                                <span style="flex: 1; text-decoration: ${t.completed ? 'line-through' : 'none'}; color: ${t.completed ? '#888' : '#333'};">${t.title}</span>
                                <button onclick="deleteTask(${t.id})" style="padding: 5px 10px; background: #f44336; color: white; border: none; border-radius: 4px; cursor: pointer;">✕</button>
                            </div>
                        `).join('');
                    }

                    renderTasks();


}
function main() {
                        console.log("╔══════════════════════════════════════╗");
                        console.log("║   OMNI - Fullstack Task Manager      ║");
                        console.log("╚══════════════════════════════════════╝");
                        console.log("");
                        console.log("Layers:");
                        console.log("  @entity Task { id, title, completed }");
                        console.log("  @server GET/POST/DELETE /api/tasks");
                        console.log("  @ui.screen TaskManager");
                        console.log("");
                        create_web_ui();
                        console.log("✓ Fullstack app running!");
}

module.exports = { print, api_get_tasks, api_create_task, api_delete_task, create_web_ui, main };

if (typeof main === 'function') { main(); }
