# Generated by Omni Compiler
import sys
import codecs
try:
    if sys.stdout.encoding != 'utf-8':
        sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

class Console:
    def log(self, *args): print(*args)
    def error(self, *args): print("ERROR:", *args)

console = Console()

# ===== INLINE: std/ui.omni =====
ui_root_ref = 0
class WindowConfig:
    def __init__(self, data=None):
        if data is None: data = {}
        self.title = data.get('title');
        self.width = data.get('width');
        self.height = data.get('height');
        self.background = data.get('background');

class Window:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle');
        self.id = data.get('id');

class Button:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle');
        self.id = data.get('id');
        self.text = data.get('text');

class Label:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle');
        self.id = data.get('id');
        self.text = data.get('text');

class TextInput:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle');
        self.id = data.get('id');

def Window_create(config):
    win = Window({ 'handle': 0, 'id': "main" })


    import tkinter as tk
    global ui_root_ref
    if ui_root_ref == 0 or ui_root_ref is None:
        ui_root_ref = tk.Tk()

    ui_root_ref.title(config.title)
    ui_root_ref.geometry(f"{config.width}x{config.height}")
    if config.background:
        ui_root_ref.configure(bg=config.background)

    win.handle = ui_root_ref

    return win
def Button_create(win, text, x, y):
    btn = Button({ 'handle': 0, 'id': "btn_" + text, 'text': text })


    import tkinter as tk
    b = tk.Button(win.handle, text=text)
    b.place(x=x, y=y)
    btn.handle = b

    return btn
def Button_set_click(btn, callback):


    if btn.handle:
        btn.handle.configure(command=callback)

def Label_create(win, text, x, y):
    lbl = Label({ 'handle': 0, 'id': "lbl", 'text': text })


    import tkinter as tk
    l = tk.Label(win.handle, text=text, bg=win.handle['bg'])
    l.place(x=x, y=y)
    lbl.handle = l

    return lbl
def Label_set_text(lbl, text):


    if lbl.handle:
        lbl.handle.configure(text=text)

def TextInput_create(win, x, y):
    inp = TextInput({ 'handle': 0, 'id': "input" })


    import tkinter as tk
    i = tk.Entry(win.handle)
    i.place(x=x, y=y)
    inp.handle = i

    return inp
def TextInput_get_value(inp):
    val = ""


    if inp.handle:
        val = inp.handle.get()

    return val
def Window_bind_key(win, key, callback):


    if win.handle:
        # Map common keys
        k = key
        if key == "ArrowLeft": k = "Left"
        elif key == "ArrowRight": k = "Right"
        elif key == "ArrowUp": k = "Up"
        elif key == "ArrowDown": k = "Down"

        win.handle.bind(f"<{k}>", lambda e: callback())

def UI_run():


    global ui_root_ref
    if ui_root_ref:
        ui_root_ref.mainloop()

# ===== END: std/ui.omni =====

# ===== INLINE: std/core.omni =====
def print_opt(msg, show_ui):

    
    import sys
    # Console output
    sys.stdout.write(str(msg) + '\n')
    sys.stdout.flush()
    
    # UI Output (Tkinter)
    if show_ui:
        try:
            import tkinter as tk
            if not hasattr(sys, 'omni_root') or sys.omni_root is None:
                sys.omni_root = tk.Tk()
                sys.omni_root.title("Omni App Logs")
                sys.omni_root.geometry("600x400")
                sys.omni_root.configure(bg="#1a1a2e")
                
                sys.omni_text = tk.Text(sys.omni_root, bg="#1a1a2e", fg="#0f0", font=("Consolas", 10))
                sys.omni_text.pack(expand=True, fill='both')
                
                # Handle close
                def on_close():
                    sys.omni_root.destroy()
                    sys.omni_root = None
                sys.omni_root.protocol("WM_DELETE_WINDOW", on_close)
    
            if sys.omni_root:
                sys.omni_text.insert(tk.END, str(msg) + "\n")
                sys.omni_text.see(tk.END)
                sys.omni_root.update()
        except Exception as e:
            sys.stderr.write(f"UI Error: {e}\n")
        
def print(msg):
    print_opt(msg, True);
def to_string(n):
    result = ""

    
    result = str(n)
        
    return result
def to_string_f(n):
    result = ""

    
    result = str(n)
        
    return result
def to_string_b(b):
    result = ""

    
    result = 'true' if b else 'false'
        
    return result
# ===== END: std/core.omni =====

name_input = TextInput({ 'handle': 0, 'id': "" })
greeting_label = Label({ 'handle': 0, 'id': "", 'text': "" })
def on_greet_click():
    name = TextInput_get_value(name_input)
    if name == "":
        name = "World";
    Label_set_text(greeting_label, "Hello, " + name + "!");
    console.log("Greeted: " + name);
def on_clear_click():
    Label_set_text(greeting_label, "");
    console.log("Cleared greeting");
def main():

    global name_input, greeting_label

    console.log("╔══════════════════════════════════════╗");
    console.log("║   OMNI - STD/UI Library Demo         ║");
    console.log("╚══════════════════════════════════════╝");
    console.log("");
    config = WindowConfig({ 'title': "STD/UI Demo App", 'width': 400, 'height': 300, 'background': "#f0f0f0" })
    win = Window_create(config)
    console.log("[OK] Window created using Window_create()");
    title_label = Label_create(win, "Welcome to Omni STD/UI", 20, 20)
    console.log("[OK] Label created using Label_create()");
    name_label = Label_create(win, "Enter your name:", 20, 60)
    name_input = TextInput_create(win, 20, 90);
    console.log("[OK] TextInput created using TextInput_create()");
    greet_btn = Button_create(win, "Greet", 20, 130)
    Button_set_click(greet_btn, on_greet_click);
    console.log("[OK] Button created with Button_on_click()");
    clear_btn = Button_create(win, "Clear", 100, 130)
    Button_set_click(clear_btn, on_clear_click);
    greeting_label = Label_create(win, "", 20, 180);
    console.log("");
    console.log("All UI created using std/ui library functions!");
    console.log("No native blocks needed in main code.");
    console.log("");
    UI_run();

__all__ = ["on_greet_click", "on_clear_click", "main"]

if __name__ == '__main__':
    if 'main' in globals():
        main()
