// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function json_demo() {{
        
                const obj = { name: "Alice", age: 30 };
                console.log("   Original: ", obj);
                const str = JSON.stringify(obj);
                console.log("   Stringified: " + str);
                const parsed = JSON.parse(str);
                console.log("   Parsed back: ", parsed);
            

}}
function main() {{
            print("╔══════════════════════════════════════╗");
            print("║   OMNI - JSON Transformer            ║");
            print("╚══════════════════════════════════════╝");
            print("");
            print("1. JSON Operations:");
            json_demo();
            print("");
            print("2. JSON Features:");
            print("   - Parse strings to objects");
            print("   - Stringify objects to strings");
            print("   - Works on JS and Python");
            print("");
            print("✓ JSON transformer example completed!");
}}

if (typeof main === 'function') main();
