// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
        print_opt(msg, true);
}
function to_string(n) {
            let result = "";
             result = String(n); 

            return result;
}
function to_string_f(n) {
                let result = "";
                 result = String(n); 

                return result;
}
function to_string_b(b) {
                    let result = "";
                     result = b ? 'true' : 'false'; 

                    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/json.omni =====
function json_parse(str) {
    let result = 0;
    
            try {
                result = JSON.parse(str);
            } catch (e) {
                console.error("JSON parse error: " + e.message);
            }
        

    return result;
}
function json_stringify(obj) {
        let result = "";
        
                try {
                    result = JSON.stringify(obj, null, 2);
                } catch (e) {
                    console.error("JSON stringify error: " + e.message);
                }
            

        return result;
}
function json_get(obj, key) {
            let value = 0;
            
                    value = obj[key];
                

            return value;
}
// ===== END: std/json.omni =====

function json_demo() {
    let q = "\\\"";
    let json_str = "{" + q + "name" + q + ": " + q + "Alice" + q + ", " + q + "age" + q + ": 30}";
    console.log("   Original JSON String: " + json_str);
    let obj = json_parse(json_str);
    let name = json_get(obj, "name");
    console.log("   Parsed Name: " + name);
    let str = json_stringify(obj);
    console.log("   Stringified back: " + str);
}
function main() {
        console.log("╔══════════════════════════════════════╗");
        console.log("║   OMNI - JSON Transformer            ║");
        console.log("╚══════════════════════════════════════╝");
        console.log("");
        console.log("1. JSON Operations:");
        json_demo();
        console.log("");
        console.log("2. JSON Features:");
        console.log("   - Parse strings to objects");
        console.log("   - Stringify objects to strings");
        console.log("   - Works on JS and Python");
        console.log("");
        console.log("✓ JSON transformer example completed!");
}

module.exports = { json_demo, main };

if (typeof main === 'function') { main(); }
