// Generated by Omni Compiler
'use strict';


function print(msg) {
console.log(msg);

}

class User {
    constructor(data = {}) {
        this.id = data.id;
        this.name = data.name;
        this.email = data.email;
    }
}

function saveUser(name, email) {
    print("Saving user: " + name + " <" + email + ">");
    return true;
}

function deleteUser(id) {
    print("Deleting user with id: " + to_string(id));
    return true;
}

function listUsers() {
    print("=== User List ===");
    print("1. Alice (alice@example.com)");
    print("2. Bob (bob@example.com)");
    print("3. Charlie (charlie@example.com)");
}

function updateUser(id, name, email) {
    print("Updating user " + to_string(id) + ": " + name);
    return true;
}

function main() {
    print("╔════════════════════════════════════════╗");
    print("║   OMNI - Universal CRUD Test           ║");
    print("╚════════════════════════════════════════╝");
    print("");
    listUsers();
    print("");
    print("--- Creating User ---");
    saveUser("David", "david@example.com");
    print("");
    print("--- Updating User ---");
    updateUser(1, "Alice Updated", "alice.new@example.com");
    print("");
    print("--- Deleting User ---");
    deleteUser(2);
    print("");
    print("✅ Universal CRUD Test Complete!");
}


// Auto-Main Invocation (Phase 6 Parity)
if (typeof main === 'function') {
    main();
}
