# Generated by Omni Compiler
import sys

def omni_print(val):
    if val is True: print('true')
    elif val is False: print('false')
    else: print(val)

def to_string(val):
    return str(val)



class User:
    def __init__(self, data=None):
        if data is None: data = {}
        self.id = data.get('id')
        self.name = data.get('name')
        self.email = data.get('email')

def saveUser(name, email):
    omni_print((((("Saving user: " + name) + " <") + email) + ">"))
    return True

def deleteUser(id):
    omni_print(("Deleting user with id: " + to_string(id)))
    return True

def listUsers():
    omni_print("=== User List ===")
    omni_print("1. Alice (alice@example.com)")
    omni_print("2. Bob (bob@example.com)")
    omni_print("3. Charlie (charlie@example.com)")

def updateUser(id, name, email):
    omni_print(((("Updating user " + to_string(id)) + ": ") + name))
    return True

def main():
    omni_print("╔════════════════════════════════════════╗")
    omni_print("║   OMNI - Universal CRUD Test           ║")
    omni_print("╚════════════════════════════════════════╝")
    omni_print("")
    listUsers()
    omni_print("")
    omni_print("--- Creating User ---")
    saveUser("David", "david@example.com")
    omni_print("")
    omni_print("--- Updating User ---")
    updateUser(1, "Alice Updated", "alice.new@example.com")
    omni_print("")
    omni_print("--- Deleting User ---")
    deleteUser(2)
    omni_print("")
    omni_print("✅ Universal CRUD Test Complete!")


if __name__ == "__main__":
    main()
