// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function deep_call_1() {{
        return deep_call_2();
}}
function deep_call_2() {{
            return deep_call_3();
}}
function deep_call_3() {{
                return deep_call_4();
}}
function deep_call_4() {{
                    return deep_call_5();
}}
function deep_call_5() {{
                        return "Deep reached!";
}}
function nested_conditionals(n) {{
                                                    if (n > 10) {{
                                                                                                    if (n > 20) {{
                                                                                                                                                if (n > 30) {{
                                                                                                                                                                                        return "very high";
                                                                                                                                                }} else {{
                                                                                                                                                                                            return "high";
                                                                                                                                                }}
                                                                                                    }} else {{
                                                                                                                                                    return "medium";
                                                                                                    }}
                                                    }} else {{
                                                                                                        return "low";
                                                    }}
}}
function main() {{
                                                        print("╔══════════════════════════════════════╗");
                                                        print("║   OMNI - Stress Nesting              ║");
                                                        print("╚══════════════════════════════════════╝");
                                                        print("");
                                                        print("1. Deep Function Calls:");
                                                        let result = deep_call_1();
                                                        print("   Result: " + result);
                                                        print("");
                                                        print("2. Nested Conditionals:");
                                                        print("   5 -> " + nested_conditionals(5));
                                                        print("   15 -> " + nested_conditionals(15));
                                                        print("   25 -> " + nested_conditionals(25));
                                                        print("   35 -> " + nested_conditionals(35));
                                                        print("");
                                                        print("✓ Stress nesting test completed!");
}}

if (typeof main === 'function') main();
