// Generated by Omni Compiler
'use strict';


function print(msg) {
console.log(msg);

}

let scene = new Scene3D({ handle: 0 });

let camera = new Camera3D({ handle: 0 });

let renderer = new Renderer3D({ handle: 0 });

let sun = new Mesh3D({ handle: 0 });

let earth = new Mesh3D({ handle: 0 });

let moon = new Mesh3D({ handle: 0 });

let time = 0;

function animate() {

    time = time + 0.01;
    let ex = cos(time) * 7;
    let ez = sin(time) * 7;
    Mesh_set_position(earth, ex, 0, ez);
    let mx = ex + cos(time * 5) * 1.5;
    let mz = ez + sin(time * 5) * 1.5;
    Mesh_set_position(moon, mx, 0, mz);
    Renderer_render(renderer, scene, camera);
}

function init() {

    scene = Scene_create();
    camera = Camera_create();
    renderer = Renderer_create();
    Renderer_init(renderer);
    Camera_set_z(camera, 15);
    sun = Sphere_create(2, 16776960, scene);
    earth = Sphere_create(0.5, 30719, scene);
    moon = Sphere_create(0.15, 8947848, scene);
    AnimationLoop(animate);
}

function main() {
    print("Starting Solar System Animation...");
    print("Note: This example is best viewed with --web flag.");
    ThreeJS_load(init);
}


// Auto-Main Invocation (Phase 6 Parity)
if (typeof main === 'function') {
    main();
}
