// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {{
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}}
function print(msg) {{
    print_opt(msg, true);
}}
function to_string(n) {{
    let result = "";
     result = String(n); 

    return result;
}}
function to_string_f(n) {{
    let result = "";
     result = String(n); 

    return result;
}}
function to_string_b(b) {{
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}}
// ===== END: std/core.omni =====

function math_add(a, b) {{
    return a + b;
}}
function math_sub(a, b) {{
    return a - b;
}}
function math_mul(a, b) {{
    return a * b;
}}
function string_repeat(s, n) {{
    let result = "";
    let i = 0;
    while (i < n) {{
            ;
            ;
    }}
    return result;
}}
function main() {{
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - Capsule Architecture        ║");
    print("╚══════════════════════════════════════╝");
    print("");
    print("Using math functions:");
    print("  10 + 5 = " + to_string(math_add(10, 5)));
    print("  10 - 5 = " + to_string(math_sub(10, 5)));
    print("  10 * 5 = " + to_string(math_mul(10, 5)));
    print("");
    print("Using string_repeat:");
    print("  repeat('*', 10) = " + string_repeat("*", 10));
    print("");
    print("✓ Modular architecture example completed!");
}}

if (typeof main === 'function') main();
