// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function math_add(a, b) {{
        return a + b;
}}
function math_sub(a, b) {{
            return a - b;
}}
function math_mul(a, b) {{
                return a * b;
}}
function string_repeat(s, n) {{
                    let result = "";
                    let i = 0;
                        while (i < n) {{
                                                ;
                                                ;
                        }}
                        return result;
}}
function main() {{
                            print("╔══════════════════════════════════════╗");
                            print("║   OMNI - Capsule Architecture        ║");
                            print("╚══════════════════════════════════════╝");
                            print("");
                            print("Using math functions:");
                            print("  10 + 5 = " + math_add(10, 5));
                            print("  10 - 5 = " + math_sub(10, 5));
                            print("  10 * 5 = " + math_mul(10, 5));
                            print("");
                            print("Using string_repeat:");
                            print("  repeat('*', 10) = " + string_repeat("*", 10));
                            print("");
                            print("✓ Modular architecture example completed!");
}}

if (typeof main === 'function') main();
