// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
        print_opt(msg, true);
}
function to_string(n) {
            let result = "";
             result = String(n); 

            return result;
}
function to_string_f(n) {
                let result = "";
                 result = String(n); 

                return result;
}
function to_string_b(b) {
                    let result = "";
                     result = b ? 'true' : 'false'; 

                    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/uuid.omni =====
function UUID_v4() {
    let result = "";
    
            // Simple v4 implementation
            result = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        

    return result;
}
function UUID_short() {
        let result = "";
        
                result = Math.random().toString(36).substring(2, 8);
            

        return result;
}
// ===== END: std/uuid.omni =====

function generate_node_id() {
    return "node_" + UUID_short();
}
function simulate_broadcast(from, msg) {
        console.log("   [" + from + "] Broadcasting: " + msg);
}
function main() {
            console.log("╔══════════════════════════════════════╗");
            console.log("║   OMNI - P2P Mesh Node               ║");
            console.log("╚══════════════════════════════════════╝");
            console.log("");
            console.log("1. Creating Nodes:");
            let node1 = generate_node_id();
            let node2 = generate_node_id();
            let node3 = generate_node_id();
            console.log("   Node 1: " + node1);
            console.log("   Node 2: " + node2);
            console.log("   Node 3: " + node3);
            console.log("");
            console.log("2. Simulating Network:");
            simulate_broadcast(node1, "Hello mesh!");
            simulate_broadcast(node2, "ACK received");
            simulate_broadcast(node3, "Joining network");
            console.log("");
            console.log("✓ P2P mesh example completed!");
}

module.exports = { generate_node_id, simulate_broadcast, main };

if (typeof main === 'function') { main(); }
