const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const OMNIC_PATH = '..\\omnic\\target\\release\\omnic.exe';

const tasks = [
    { src: 'src/core/token.omni', dest: 'dist/core/token.js' },
    { src: 'src/core/lexer.omni', dest: 'dist/core/lexer.js' },
    { src: 'src/core/ast.omni', dest: 'dist/core/ast.js' },
    { src: 'src/core/parser.omni', dest: 'dist/core/parser.js' },
    { src: 'src/core/codegen.omni', dest: 'dist/core/codegen.js' },
    { src: 'src/core/io.omni', dest: 'dist/core/io.js' },
    { src: 'src/main.omni', dest: 'dist/main.js' }
];

function bootstrapV1() {
    console.log('=== Bootstrapping V1 (Rust -> V2) ===');
    
    // Ensure dist structure
    if (!fs.existsSync('dist/core')) fs.mkdirSync('dist/core', { recursive: true });

    for (const task of tasks) {
        console.log(`Compiling ${task.src} -> ${task.dest}`);
        try {
            // Using build command, assuming it outputs execution logs to stderr and code to stdout
            // But wait, the previous run showed "Compilando Arquivo..." mixed with code?
            // "Compilando Arquivo: src/core/token.omni -> Js" is likely LOG.
            // "// Generated by Omni Compiler" is CODE.
            // I need to separate them if they are on same stream.
            // If logs are on stderr and code on stdout, it's easy.
            // If both on stdout, I need to filter.
            
            // Let's assume logs are Stderr or I can suppress them?
            // The rust compiler 'println!' usually goes to stdout. 'eprintln!' to stderr.
            // If logs are on stdout, I will have to filter the first line if it starts with "Compilando".
            
            const output = execSync(`${OMNIC_PATH} build ${task.src}`, { encoding: 'utf8' });
            
            // Heuristic to clean output:
            // Remove lines that don't look like code?
            // "Compilando Arquivo: ..."
            const lines = output.split('\n');
            const codeLines = lines.filter(l => !l.startsWith('Compilando Arquivo:') && !l.startsWith('>> '));
            const code = codeLines.join('\n').trim();
            
            fs.writeFileSync(task.dest, code);
            console.log('OK');
        } catch (e) {
            console.error('Failed', e);
            process.exit(1);
        }
    }
}

bootstrapV1();
