$ErrorActionPreference = "Stop"
$Omnic = "..\omnic\target\release\omnic.exe"
$Dist = "dist"

# Ensure dirs
New-Item -ItemType Directory -Force "$Dist\core" | Out-Null
New-Item -ItemType Directory -Force "$Dist\lib" | Out-Null
New-Item -ItemType Directory -Force "$Dist\commands" | Out-Null

$Core = @("token", "lexer", "parser", "ast", "codegen", "codegen_hybrid", "vm", "framework_adapter", "ingestion", "package_manager", "contracts", "ghost_writer", "bootstrap", "studio_engine", "studio_graph", "app_packager", "tui")
$Lib = @("std", "cli", "terminal")
$Cmds = @("cmd_setup", "cmd_run", "cmd_build", "cmd_test", "cmd_package", "cmd_registry", "cmd_studio")

function Compile($file, $out) {
    Write-Host "Compiling $file"
    $c = & $Omnic build $file --target js
    $filtered = $c | Where-Object { $_ -notmatch "Compilando Arquivo:" }
    Set-Content -Path $out -Value $filtered -Encoding UTF8
}

foreach ($m in $Core) { Compile "src/core/$m.omni" "$Dist/core/$m.js" }
foreach ($m in $Lib) { Compile "src/lib/$m.omni" "$Dist/lib/$m.js" }
foreach ($m in $Cmds) { Compile "src/commands/$m.omni" "$Dist/commands/$m.js" }

Write-Host "Compiling main"
Compile "src/main.omni" "$Dist/main.js"

Write-Host "Bundling..."

# Simple concatenation - no IIFEs, all functions in global scope
# Global Header: Define core Node.js dependencies once at the top
$bundle = @"
'use strict';
// Omni Compiler Bundle
// Global Header: Core Node.js dependencies
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

"@

function AppendModule($path) {
    if (Test-Path $path) {
        $content = Get-Content $path -Raw
        # Remove ONLY top-level require statements (at column 0) - preserves requires inside native blocks
        # Using (?m) multiline mode with ^ anchor to match only lines starting with 'const'
        $content = $content -replace "(?m)^const\s+\w+\s*=\s*require\([^)]+\);\s*`r?`n?", ""
        # Remove 'use strict' since we have it at top
        $content = $content -replace "'use strict';", ""
        # Remove '// Generated by Omni Compiler' comment lines
        $content = $content -replace "// Generated by Omni Compiler`r?`n?", ""
        return "`n$content`n"
    }
    return ""
}

# Load in dependency order: core, lib, commands, main
foreach ($m in $Core) { $bundle += AppendModule "$Dist/core/$m.js" }
foreach ($m in $Lib) { $bundle += AppendModule "$Dist/lib/$m.js" }
foreach ($m in $Cmds) { $bundle += AppendModule "$Dist/commands/$m.js" }
$bundle += AppendModule "$Dist/main.js"

# main.js already contains the entry point from compilation, no need to add another

Set-Content "$Dist/omni_bundle.js" -Value $bundle -Encoding UTF8
Write-Host "Done: $Dist/omni_bundle.js"
