// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 
}}
function input_node(value) {{
        return value;
}}
function process_node(input) {{
            return "Processed: " + input;
}}
function output_node(result) {{
                print("Output: " + result);
}}
function create_ui() {{
                    
                            document.body.innerHTML = `
                                <div style="padding: 20px; font-family: sans-serif;">
                                    <h1>Interactive UI Nodes</h1>
                                    <div style="display: flex; gap: 20px; margin-top: 20px;">
                                        <div style="padding: 20px; background: #4CAF50; color: white; border-radius: 8px;">
                                            <h3>Input Node</h3>
                                            <input id="input" type="text" value="Hello" style="padding: 8px;">
                                        </div>
                                        <div style="padding: 20px; background: #2196F3; color: white; border-radius: 8px;">
                                            <h3>Process Node</h3>
                                            <button onclick="processData()" style="padding: 8px 16px;">Process</button>
                                        </div>
                                        <div style="padding: 20px; background: #FF9800; color: white; border-radius: 8px;">
                                            <h3>Output Node</h3>
                                            <div id="output">-</div>
                                        </div>
                                    </div>
                                </div>
                            `;
                            
                            window.processData = function() {
                                const input = document.getElementById('input').value;
                                const result = "Processed: " + input;
                                document.getElementById('output').textContent = result;
                            };
                        
}}
function main() {{
                        print("Starting Interactive UI Nodes...");
                        create_ui();
}}
