# Generated by Omni Compiler

# Decorator stubs
def entity(cls):
    return cls

def ui(*args, **kwargs):
    def decorator(func):
        return func
    return decorator

def print(msg):

    print(msg)

def classify_number(n):
    if n < 0:
        return 'negative'

    else:
        if n == 0:
            return 'zero'

        else:
            if n < 10:
                return 'small positive'

            else:
                if n < 100:
                    return 'medium positive'

                else:
                    return 'large positive'





def factorial(n):
    result = 1
    i = 1
    while i <= n:
        result = result
        # Unknown stmt: 0
        i
        i = i + 1

    return result

def fibonacci(n):
    if n <= 1:
        return n

    return fibonacci(n, None, 1) + fibonacci(n, None, 2)

def print_table(size):
    i = 1
    while i <= size:
        j = 1
        row = ''
        while j <= size:
            product = i
            # Unknown stmt: 0
            j

            j = j + 1

        print('  ' + row)
        i = i + 1


def find_first_divisible(start, divisor, limit):
    n = start
    while n <= limit:

        n = n + 1

    return None
    1

def main():
    print('╔══════════════════════════════════════╗')
    print('║   OMNI - Flow Control Example        ║')
    print('╚══════════════════════════════════════╝')
    print('')
    print('1. Conditionals (if/else):')
    print('   -5 is ' + classify_number(None, 5))
    print('   0 is ' + classify_number(0))
    print('   7 is ' + classify_number(7))
    print('   42 is ' + classify_number(42))
    print('   999 is ' + classify_number(999))
    print('')
    print('2. While Loops (factorial):')
    f5 = factorial(5)
    f7 = factorial(7)
    print('   5! = 120')
    print('   7! = 5040')
    print('')
    print('3. Recursion (fibonacci):')
    print('   fib(10) = 55')
    print('   fib(15) = 610')
    print('')
    print('4. Nested Loops (3x3 multiplication table):')
    print_table(3)
    print('')
    print('5. Early Return Pattern:')
    first = find_first_divisible(10, 7, 100)
    print('   First number divisible by 7 after 10: 14')
    print('')
    print('✓ Flow control example completed!')


if __name__ == "__main__":
    main()
