# Generated by Omni Compiler

# Decorator stubs
def entity(cls):
    return cls

def ui(*args, **kwargs):
    def decorator(func):
        return func
    return decorator

def print(msg):


@entity
class Task:
    def __init__(self, data=None):
        if data is None: data = {}
        self.id = data.get('id')
        self.title = data.get('title')
        self.completed = data.get('completed')
        self.priority = data.get('priority')


@entity
class User:
    def __init__(self, data=None):
        if data is None: data = {}
        self.id = data.get('id')
        self.name = data.get('name')
        self.email = data.get('email')


return False

if __name__ == "__main__":
    main()
