/* Generated by Omni Compiler (Target: ANSI C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

// --- Omni Memory Management ---
typedef struct { int _ref_count; } OmniRef;
void omni_retain(void* ptr) {
    if (ptr) ((OmniRef*)ptr)->_ref_count++;
}
void omni_release(void* ptr) {
    if (ptr) {
        ((OmniRef*)ptr)->_ref_count--;
        if (((OmniRef*)ptr)->_ref_count <= 0) free(ptr);
    }
}
// ------------------------------

typedef void* Any;

/* Capsule: Main */
void Main_main() {
    /* expr */("Hello from C-Native Omni!");
    // Unsupported statement in C prototype
    /* expr */(x);
}

