// Generated by Omni Compiler
'use strict';


const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { spawnSync } = require('child_process');

const examplesDir = __dirname;

// ANSI Colors
const colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    dim: '\x1b[2m',
    green: '\x1b[32m',
    cyan: '\x1b[36m',
    yellow: '\x1b[33m',
    magenta: '\x1b[35m',
    red: '\x1b[31m'
};

// Find all examples with omni.conf.json
function findExamples() {
    const entries = fs.readdirSync(examplesDir, { withFileTypes: true });
    const examples = [];

    for (const entry of entries) {
        if (entry.isDirectory()) {
            const confPath = path.join(examplesDir, entry.name, 'omni.conf.json');
            if (fs.existsSync(confPath)) {
                const conf = JSON.parse(fs.readFileSync(confPath, 'utf-8'));
                examples.push({
                    folder: entry.name,
                    name: conf.name || entry.name,
                    description: conf.description || '',
                    entry: conf.entry || 'src/main.omni',
                    modes: conf.targets || ['cmd'],
                    defaultMode: conf.defaultMode || 'cmd'
                });
            }
        }
    }

    return examples.sort((a, b) => a.folder.localeCompare(b.folder));
}

// Display banner
function showBanner() {
    console.clear();
    console.log(colors.cyan + '╔════════════════════════════════════════════════════════════════╗');
    console.log('║                    🎨 OMNI EXAMPLES HUB                        ║');
    console.log('╚════════════════════════════════════════════════════════════════╝' + colors.reset);
    console.log('');
}

// Display examples list
function showExamples(examples) {
    console.log(colors.bright + 'Available Examples:' + colors.reset);
    console.log('');

    examples.forEach((ex, i) => {
        const modes = ex.modes.map(m => {
            if (m === 'cmd') return colors.green + m + colors.reset;
            if (m === 'app') return colors.magenta + m + colors.reset;
            if (m === 'web') return colors.cyan + m + colors.reset;
            if (m === 'web-app') return colors.yellow + m + colors.reset;
            return m;
        }).join(', ');

        console.log(`  ${colors.bright}${(i + 1).toString().padStart(2, ' ')}${colors.reset}. ${ex.folder}`);
        console.log(`      ${colors.dim}${ex.description}${colors.reset}`);
        console.log(`      Modes: [${modes}]`);
        console.log('');
    });
}

// Display mode selection
function showModes(example) {
    console.log('');
    console.log(colors.bright + `Selected: ${example.name}` + colors.reset);
    console.log(colors.dim + example.description + colors.reset);
    console.log('');
    console.log('Available modes:');

    example.modes.forEach((mode, i) => {
        let desc = '';
        if (mode === 'cmd') desc = 'Terminal execution';
        if (mode === 'app') desc = 'Native desktop app (Tkinter)';
        if (mode === 'web') desc = 'Web server (http://localhost:3000)';
        if (mode === 'web-app') desc = 'Web + opens browser automatically';

        const isDefault = mode === example.defaultMode ? ' (default)' : '';
        console.log(`  ${i + 1}. ${colors.bright}--${mode}${colors.reset} - ${desc}${isDefault}`);
    });
    console.log('');
}

// Run example
function runExample(example, mode) {
    const entryPath = path.join(examplesDir, example.folder, example.entry);
    const omniPath = path.join(examplesDir, '..', 'omni');

    console.log('');
    console.log(colors.cyan + `Running: omni run ${entryPath} --${mode}` + colors.reset);
    console.log('');

    const result = spawnSync('node', [
        path.join(examplesDir, '..', 'omnic-v2', 'dist', 'main.js'),
        'run',
        entryPath,
        '--' + mode
    ], { stdio: 'inherit' });
}

// Main menu
async function hub_main() {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    const question = (prompt) => new Promise(resolve => rl.question(prompt, resolve));

    while (true) {
        showBanner();
        const examples = findExamples();
        showExamples(examples);

        console.log(colors.dim + 'Enter example number (or q to quit):' + colors.reset);
        const choice = await question('> ');

        if (choice.toLowerCase() === 'q') {
            rl.close();
            console.log('Bye!');
            process.exit(0);
        }

        const exIndex = parseInt(choice) - 1;
        if (isNaN(exIndex) || exIndex < 0 || exIndex >= examples.length) {
            console.log(colors.red + 'Invalid choice. Press Enter to continue...' + colors.reset);
            await question('');
            continue;
        }

        const selectedExample = examples[exIndex];
        showBanner();
        showModes(selectedExample);

        console.log(colors.dim + 'Enter mode number (or b to go back):' + colors.reset);
        const modeChoice = await question('> ');

        if (modeChoice.toLowerCase() === 'b') {
            continue;
        }

        const modeIndex = parseInt(modeChoice) - 1;
        if (isNaN(modeIndex) || modeIndex < 0 || modeIndex >= selectedExample.modes.length) {
            console.log(colors.red + 'Invalid mode. Press Enter to continue...' + colors.reset);
            await question('');
            continue;
        }

        const selectedMode = selectedExample.modes[modeIndex];
        runExample(selectedExample, selectedMode);

        console.log('');
        console.log(colors.dim + 'Press Enter to return to menu...' + colors.reset);
        await question('');
    }
}

hub_main().catch(console.error);


if (typeof main === 'function') { main(); }
