# Generated by Omni Compiler

def log(msg):

    
    print(str(msg))
        
def render_cube(size, color):

        
        try:
            import tkinter as tk
            # APP - Tkinter Canvas
            root = tk.Tk()
            root.title("Omni 3D Cube")
            root.configure(bg='#1a1a2e')
            canvas = tk.Canvas(root, width=400, height=400, bg='#1a1a2e', highlightthickness=0)
            canvas.pack(padx=20, pady=20)
            
            cx, cy = 200, 200
            s = size * 30
            off = s // 2
            c = color
            # Front face
            canvas.create_polygon(cx-s, cy-s, cx+s, cy-s, cx+s, cy+s, cx-s, cy+s, outline=c, fill='', width=2)
            # Back face
            canvas.create_polygon(cx-s+off, cy-s-off, cx+s+off, cy-s-off, cx+s+off, cy+s-off, cx-s+off, cy+s-off, outline=c, fill='', width=2)
            # Edges
            canvas.create_line(cx-s, cy-s, cx-s+off, cy-s-off, fill=c, width=2)
            canvas.create_line(cx+s, cy-s, cx+s+off, cy-s-off, fill=c, width=2)
            canvas.create_line(cx+s, cy+s, cx+s+off, cy+s-off, fill=c, width=2)
            canvas.create_line(cx-s, cy+s, cx-s+off, cy+s-off, fill=c, width=2)
            canvas.create_text(200, 380, text="Omni 3D Cube", fill='white', font=('Arial', 14))
            
            root.mainloop()
        except:
            # Fallback ASCII
            print('')
            print('    +-------+')
            print('   /       /|')
            print('  /       / |')
            print(' +-------+  |')
            print(' |       |  +')
            print(' |       | /')
            print(' |       |/')
            print(' +-------+')
            
def main():
            log("╔══════════════════════════════════════╗");
            log("║   OMNI - 3D Cube (Universal)         ║");
            log("╚══════════════════════════════════════╝");
            log("");
            render_cube(2, "#00ff00");

if __name__ == '__main__':
    main()
