// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 
}}
function create_scene() {{
        
                // Dynamically load Three.js
                const script = document.createElement('script');
                script.src = 'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js';
                script.onload = function() {
                    initScene();
                };
                document.head.appendChild(script);
            
}}
function initScene() {{
            
                    const scene = new THREE.Scene();
                    const camera = new THREE.PerspectiveCamera(75, window.innerWidth/window.innerHeight, 0.1, 1000);
                    const renderer = new THREE.WebGLRenderer();
                    renderer.setSize(window.innerWidth, window.innerHeight);
                    document.body.appendChild(renderer.domElement);
                    
                    // Create cube
                    const geometry = new THREE.BoxGeometry();
                    const material = new THREE.MeshBasicMaterial({ color: 0x00ff00, wireframe: true });
                    const cube = new THREE.Mesh(geometry, material);
                    scene.add(cube);
                    
                    camera.position.z = 5;
                    
                    // Animation loop
                    function animate() {
                        requestAnimationFrame(animate);
                        cube.rotation.x += 0.01;
                        cube.rotation.y += 0.01;
                        renderer.render(scene, camera);
                    }
                    animate();
                
}}
function main() {{
                print("Starting 3D Cube Demo...");
                create_scene();
}}
