# Generated by Omni Compiler

def print(msg):

def create_scene():

def initScene():

def main():
                print("Starting 3D Cube Demo...");
                create_scene();

if __name__ == '__main__':
    main()
