# Generated by Omni Compiler

# Decorator stubs
def entity(cls):
    return cls

def ui(*args, **kwargs):
    def decorator(func):
        return func
    return decorator

def print(msg):

    import sys
    sys.stdout.write(str(msg) + '\n') 

@entity
class WindowConfig:
    def __init__(self, data=None):
        if data is None: data = {}
        self.title = data.get('title')
        self.width = data.get('width')
        self.height = data.get('height')
        self.resizable = data.get('resizable')
        self.fullscreen = data.get('fullscreen')
        self.background = data.get('background')


@entity
class Window:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.config = data.get('config')
        self.is_open = data.get('is_open')


@entity
class Button:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.label = data.get('label')
        self.x = data.get('x')
        self.y = data.get('y')
        self.width = data.get('width')
        self.height = data.get('height')


@entity
class Label:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.text = data.get('text')
        self.x = data.get('x')
        self.y = data.get('y')


@entity
class TextInput:
    def __init__(self, data=None):
        if data is None: data = {}
        self.handle = data.get('handle')
        self.placeholder = data.get('placeholder')
        self.value = data.get('value')
        self.x = data.get('x')
        self.y = data.get('y')
        self.width = data.get('width')


GUI_main_window = Window({ 'handle': 0, 'config': WindowConfig({ 'title': '', 'width': 0, 'height': 0, 'resizable': False, 'fullscreen': False, 'background': '' }), 'is_open': False })
def GUI_create_window(config):
    win = Window({ 'handle': 0, 'config': config, 'is_open': False })

    global GUI_main_window
    global main_window_ref
    global tk
    global ttk
    import tkinter as tk
    from tkinter import ttk
    root = tk.Tk()
    root.title(config.title)
    root.geometry(f"{config.width}x{config.height}")
    if config.background:
        root.configure(bg=config.background)
    if not config.resizable:
        root.resizable(False, False)
    win.handle = root
    win.is_open = True
    # Global store
    main_window_ref = root 
    GUI_main_window = win
    return win

def GUI_add_button(label, x, y, width, height):
    btn = Button({ 'handle': 0, 'label': label, 'x': x, 'y': y, 'width': width, 'height': height })
    button = ttk.Button(main_window_ref, text=label)
    button.place(x=x, y=y, width=width, height=height)
    btn.handle = button
    return btn

def GUI_add_label(text, x, y):
    lbl = Label({ 'handle': 0, 'text': text, 'x': x, 'y': y })
    # Default bg if config unavailable
    bg_color = main_window_ref.cget('bg')
    label = tk.Label(main_window_ref, text=text, bg=bg_color)
    label.place(x=x, y=y)
    lbl.handle = label
    return lbl

def GUI_add_input(placeholder, x, y, width):
    input = TextInput({ 'handle': 0, 'placeholder': placeholder, 'value': '', 'x': x, 'y': y, 'width': width })
    entry = ttk.Entry(main_window_ref)
    entry.place(x=x, y=y, width=width)
    input.handle = entry
    return input

def GUI_on_click(btn, callback):
    def wrapper():
        callback()
    btn.handle.config(command=wrapper)

def GUI_set_label_text(lbl, text):
    lbl.handle.config(text=text)

def GUI_close():
    # win.handle.destroy()
    pass

def GUI_loop():
    global main_window_ref
    main_window_ref.mainloop()

app_name_input = TextInput({ 'handle': 0, 'placeholder': '', 'value': '', 'x': 0, 'y': 0, 'width': 0 })
app_result_label = Label({ 'handle': 0, 'text': '', 'x': 0, 'y': 0 })
def on_greet():
    # access globals
    # in generated python, globals are available
    # we need to ensure the handles are valid
    val = app_name_input.handle.get()
    app_result_label.handle.config(text="Hello " + val)
    print('Button clicked!')

def main():
    print('+--------------------------------------+')
    print('|   OMNI - Desktop Window (std.gui)    |')
    print('+--------------------------------------+')
    print('')
    print('Creating native window...')
    config = WindowConfig({ 'title': 'Omni Desktop App', 'width': 400, 'height': 300, 'resizable': True, 'fullscreen': False, 'background': '#f5f5f5' })
    window = GUI_create_window(config)
    print('  [OK] Window created: ' + config.title)
    title = GUI_add_label('Welcome to Omni GUI', 20, 20)
    print('  [OK] Label added')
    app_name_input = GUI_add_input('Enter your name...', 20, 60, 200)
    print('  [OK] Input field added')
    greet_button = GUI_add_button('Greet', 20, 110, 100, 36)
    print('  [OK] Button added')
    app_result_label = GUI_add_label('', 20, 160)
    GUI_on_click(greet_button, on_greet)
    print('  [OK] Event handler bound')
    print('')
    print('[OK] Desktop window demo ready!')
    GUI_loop()
    print('  Open in browser to see the simulated window.')


if __name__ == "__main__":
    main()
