# Generated by Omni Compiler

def log(msg):

     print(msg) 
def create_tkinter_app():
        
        import tkinter as tk
        from tkinter import ttk
        
        # Create main window
        root = tk.Tk()
        root.title("Omni Desktop App")
        root.geometry("400x300")
        root.configure(bg="#f5f5f5")
        
        # Title label
        title = tk.Label(root, text="Welcome to Omni GUI", bg="#f5f5f5", font=("Helvetica", 16))
        title.place(x=20, y=20)
        
        # Name input
        name_entry = ttk.Entry(root)
        name_entry.place(x=20, y=70, width=200)
        
        # Result label
        result_label = tk.Label(root, text="", bg="#f5f5f5", font=("Helvetica", 12))
        result_label.place(x=20, y=150)
        
        # Greet button callback
        def on_greet():
            name = name_entry.get()
            if name:
                result_label.config(text=f"Hello, {name}!")
            else:
                result_label.config(text="Hello, World!")
        
        # Button
        greet_btn = ttk.Button(root, text="Greet", command=on_greet)
        greet_btn.place(x=20, y=110, width=100, height=30)
        
        print("Desktop window ready!")
        root.mainloop()
            
def main():
            log("╔══════════════════════════════════════╗");
            log("║   OMNI - Desktop Window (Tkinter)    ║");
            log("╚══════════════════════════════════════╝");
            log("");
            log("Launching native Tkinter window...");
            create_tkinter_app();
            log("");
            log("✓ Desktop window closed.");

if __name__ == '__main__':
    main()
