// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
    print_opt(msg, true);
}
function to_string(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_f(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_b(b) {
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/ui.omni =====
let ui_root_ref = 0;
class WindowConfig {
    constructor(data = {}) {
        this.title = data.title;
        this.width = data.width;
        this.height = data.height;
        this.background = data.background;
    }

}
class Window {
    constructor(data = {}) {
        this.handle = data.handle;
        this.id = data.id;
    }

}
class Button {
    constructor(data = {}) {
        this.handle = data.handle;
        this.id = data.id;
        this.text = data.text;
    }

}
class Label {
    constructor(data = {}) {
        this.handle = data.handle;
        this.id = data.id;
        this.text = data.text;
    }

}
class TextInput {
    constructor(data = {}) {
        this.handle = data.handle;
        this.id = data.id;
    }

}
function Window_create(config) {
    let win = new Window({ handle: 0, id: "main" });
    
            if (typeof document !== 'undefined') {
                const div = document.createElement('div');
                div.style.width = config.width + 'px';
                div.style.height = config.height + 'px';
                div.style.backgroundColor = config.background;
                div.style.position = 'relative';
                div.style.border = '1px solid #ccc';
                div.style.margin = '20px auto';
                div.style.fontFamily = 'sans-serif';
                div.id = 'omni-window-main';
                document.body.appendChild(div);
                win.handle = div;
            }
        

    return win;
}
function Button_create(win, text, x, y) {
    let btn = new Button({ handle: 0, id: "btn_" + text, text: text });
    
            if (typeof document !== 'undefined') {
                const b = document.createElement('button');
                b.innerText = text;
                b.style.position = 'absolute';
                b.style.left = x + 'px';
                b.style.top = y + 'px';
                if (win.handle) win.handle.appendChild(b);
                btn.handle = b;
            }
        

    return btn;
}
function Button_set_click(btn, callback) {
    
            if (btn.handle) btn.handle.onclick = callback;
        

}
function Label_create(win, text, x, y) {
    let lbl = new Label({ handle: 0, id: "lbl", text: text });
    
            if (typeof document !== 'undefined') {
                 const l = document.createElement('div');
                 l.innerText = text;
                 l.style.position = 'absolute';
                 l.style.left = x + 'px';
                 l.style.top = y + 'px';
                 if (win.handle) win.handle.appendChild(l);
                 lbl.handle = l;
            }
        

    return lbl;
}
function Label_set_text(lbl, text) {
    
            if (lbl.handle) lbl.handle.innerText = text;
        

}
function TextInput_create(win, x, y) {
    let inp = new TextInput({ handle: 0, id: "input" });
    
            if (typeof document !== 'undefined') {
                const i = document.createElement('input');
                i.type = 'text';
                i.style.position = 'absolute';
                i.style.left = x + 'px';
                i.style.top = y + 'px';
                if (win.handle) win.handle.appendChild(i);
                inp.handle = i;
            }
        

    return inp;
}
function TextInput_get_value(inp) {
    let val = "";
    
            if (inp.handle) val = inp.handle.value;
        

    return val;
}
function UI_run() {
    
            console.log("UI running (web mode)");
        

}
// ===== END: std/ui.omni =====

let name_input = new TextInput({ handle: 0, id: "" });
let result_label = new Label({ handle: 0, id: "", text: "" });
function on_greet() {
    let name = TextInput_get_value(name_input);
    if (name) {
            Label_set_text(result_label, "Hello, " + name + "!");
    } else {
            Label_set_text(result_label, "Hello, World!");
    }
}
function create_app() {
    let config = new WindowConfig({ title: "Omni GUI", width: 400, height: 300, background: "#f5f5f5" });
    let win = Window_create(config);
    Label_create(win, "Welcome to Omni GUI", 20, 20);
    ;
    let btn = Button_create(win, "Greet", 20, 110);
    Button_set_click(btn, on_greet);
    ;
    print("UI Constructed. Running loop...");
    UI_run();
}
function main() {
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - Desktop Window (Tkinter)    ║");
    print("╚══════════════════════════════════════╝");
    print("");
    print("Launching UI...");
    create_app();
    print("");
    print("✓ Desktop window closed.");
}

if (typeof main === 'function') main();
