// Generated by Omni Compiler
'use strict';

function log(msg) {{
     console.log(msg); 

}}
function create_tkinter_app() {{

}}
function main() {{
            log("╔══════════════════════════════════════╗");
            log("║   OMNI - Desktop Window (Tkinter)    ║");
            log("╚══════════════════════════════════════╝");
            log("");
            log("Launching native Tkinter window...");
            create_tkinter_app();
            log("");
            log("✓ Desktop window closed.");
}}
