// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 
}}
function create_hub() {{
        
                document.body.innerHTML = `
                    <div style="padding: 40px; font-family: sans-serif; text-align: center;">
                        <h1>🏠 Navigation Hub</h1>
                        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; max-width: 800px; margin: 40px auto;">
                            <div class="card" onclick="navigate('dashboard')">📊 Dashboard</div>
                            <div class="card" onclick="navigate('settings')">⚙️ Settings</div>
                            <div class="card" onclick="navigate('profile')">👤 Profile</div>
                            <div class="card" onclick="navigate('reports')">📈 Reports</div>
                            <div class="card" onclick="navigate('help')">❓ Help</div>
                            <div class="card" onclick="navigate('logout')">🚪 Logout</div>
                        </div>
                        <div id="content" style="margin-top: 40px; padding: 20px; background: #f5f5f5; border-radius: 8px;"></div>
                    </div>
                    <style>
                        .card { 
                            padding: 30px; 
                            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                            color: white; 
                            border-radius: 12px; 
                            cursor: pointer;
                            font-size: 18px;
                            transition: transform 0.2s;
                        }
                        .card:hover { transform: scale(1.05); }
                    </style>
                `;
                
                window.navigate = function(page) {
                    document.getElementById('content').innerHTML = 
                        '<h2>Navigating to: ' + page + '</h2>' +
                        '<p>This is the ' + page + ' page content.</p>';
                };
            
}}
function main() {{
            print("Starting Hub Navigation...");
            create_hub();
}}
