// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {{
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}}
function print(msg) {{
    print_opt(msg, true);
}}
function to_string(n) {{
    let result = "";
     result = String(n); 

    return result;
}}
function to_string_f(n) {{
    let result = "";
     result = String(n); 

    return result;
}}
function to_string_b(b) {{
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}}
// ===== END: std/core.omni =====

function create_rect(w, h) {{
    return w * h;
}}
function main() {{
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - Types and Structs           ║");
    print("╚══════════════════════════════════════╝");
    print("");
    print("1. Primitive Types:");
    let count = 42;
    let pi = 3.14159;
    let active = true;
    let name = "Omni";
    print("   i64:    count = " + to_string(count));
    print("   f64:    pi = 3.14159");
    print("   bool:   active = true");
    print("   string: name = " + name);
    print("");
    print("2. Arithmetic:");
    let sum = count + 8;
    print("   42 + 8 = " + to_string(sum));
    print("");
    print("3. Area Calculation (simulated struct):");
    let width = 10;
    let height = 5;
    let area = create_rect(width, height);
    print("   Rectangle: 10 x 5 = " + to_string_f(area));
    print("");
    print("✓ Types and primitives example completed!");
}}

if (typeof main === 'function') main();
