// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function create_rect(w, h) {{
        return w * h;
}}
function main() {{
            print("╔══════════════════════════════════════╗");
            print("║   OMNI - Types and Structs           ║");
            print("╚══════════════════════════════════════╝");
            print("");
            print("1. Primitive Types:");
            let count = 42;
            let pi = 3.14159;
            let active = true;
            let name = "Omni";
            print("   i64:    count = " + count);
            print("   f64:    pi = 3.14159");
            print("   bool:   active = true");
            print("   string: name = " + name);
            print("");
            print("2. Arithmetic:");
            let sum = count + 8;
            print("   42 + 8 = " + sum);
            print("");
            print("3. Area Calculation (simulated struct):");
            let width = 10;
            let height = 5;
            let area = create_rect(width, height);
            print("   Rectangle: 10 x 5 = " + area);
            print("");
            print("✓ Types and primitives example completed!");
}}

if (typeof main === 'function') main();
