// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
        print_opt(msg, true);
}
function to_string(n) {
            let result = "";
             result = String(n); 

            return result;
}
function to_string_f(n) {
                let result = "";
                 result = String(n); 

                return result;
}
function to_string_b(b) {
                    let result = "";
                     result = b ? 'true' : 'false'; 

                    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/os.omni =====
function os_platform() {
    let platform = "unknown";
    
            if (typeof process !== 'undefined') {
                platform = process.platform;
            } else {
                platform = "web";
            }
        

    return platform;
}
function os_time_ms() {
        let ts = 0;
        
                ts = Date.now();
            

        return ts;
}
function os_version() {
            let ver = "unknown";
            
                    if (typeof process !== 'undefined') {
                        ver = process.version;
                    } else {
                        ver = "browser";
                    }
                

            return ver;
}
// ===== END: std/os.omni =====

function main() {
    console.log("╔══════════════════════════════════════╗");
    console.log("║   OMNI - System Info                 ║");
    console.log("╚══════════════════════════════════════╝");
    console.log("");
    console.log("1. Platform Detection:");
    let platform = os_platform();
    console.log("   Platform: " + platform);
    console.log("");
    console.log("2. Timestamp:");
    let ts = os_time_ms();
    console.log("   Current timestamp: " + to_string(ts));
    console.log("");
    console.log("3. Runtime Info:");
    let ver = os_version();
    console.log("   Runtime Version: " + ver);
    console.log("");
    console.log("✓ System info example completed!");
}

module.exports = { main };

if (typeof main === 'function') { main(); }
