// Generated by Omni Compiler
'use strict';

// Capsule: OmniTester
const OmniTester = {
    EXAMPLES_DIR: "./examples",
    TARGETS: ["js", "python"],
    run_full_suite() {
    console.log("🚀 Iniciando Suite de Testes Global do Omni...");
    let results = [];
    let total_bugs = 0;
    let files = (() => {  
                const fs = require('fs');
                const path = require('path');
                const root = OmniTester.EXAMPLES_DIR;
                let all_files = [];
                
                // Get subdirectories
                const entries = fs.readdirSync(root, { withFileTypes: true });
                
                for (const entry of entries) {
                    if (entry.isDirectory()) {
                        // Check for .omni file with same name as dir or index.omni?
                        // Just find any .omni file in the dir
                        const dirPath = path.join(root, entry.name);
                        const subFiles = fs.readdirSync(dirPath).filter(f => f.endsWith('.omni'));
                        for (const sub of subFiles) {
                             // Store relative path: "01_hello/hello.omni"
                             all_files.push(entry.name + "/" + sub);
                        }
                    } else if (entry.name.endsWith('.omni')) {
                        all_files.push(entry.name);
                    }
                }
                return all_files; 
             })();
            for (const file of files) {
                    console.log("-----------------------------------------");
                    console.log("🧪 Testando: " + file);
                    let success = OmniTester.test_metamorphosis(file, OmniTester.TARGETS);
                        if (!success) {
                                    total_bugs = total_bugs + 1;
                        }}
            OmniTester.generate_report(results, total_bugs);    },
    test_metamorphosis(file, targets) {
            let outputs = [];
            let compile_errors = 0;
            let runtime_errors = 0;
                                for (const target of targets) {
                                                console.log("   -> Target: " + target);
                                                let ext_out = ".js";
                                                    if (target === "python") {
                                                                        ext_out = ".py";
                                                    }
                                                    let cmd = ".\\\\omni.bat ";
                                                    cmd = cmd + OmniTester.EXAMPLES_DIR;
                                                    cmd = cmd + "/" + file + " ";
                                                    cmd = cmd + OmniTester.EXAMPLES_DIR + "/" + file + "_out" + ext_out;
                                                    cmd = cmd + " --target " + target;
                                                    let compile_ok = (() => {  
                                                                    const { execSync } = require('child_process');
                                                                    try { 
                                                                        execSync(cmd, { stdio: 'pipe' }); 
                                                                        return true; 
                                                                    } catch(e) { 
                                                                        console.log("      ❌ Compile Error: " + e.message);
                                                                        return false; 
                                                                    }
                                                                 })();
                                                        if (!compile_ok) {
                                                                                compile_errors = compile_errors + 1;
                                                                                continue;
                                                        }
                                                        let out_val = OmniTester.validate_execution(file, target);
                                                                if (out_val === "__ERROR__") {
                                                                                            runtime_errors = runtime_errors + 1;
                                                                } else {
                                                                                                outputs.push(out_val);
                                                                }}
                                    if (compile_errors > 0 || runtime_errors > 0) {
                                                                        return false;
                                    }
                                                if (outputs.length > 1) {
                                                                                        let base = outputs;
                                                                                        [0];
                                                                                        let parity_ok = true;
                                                                                        parity_ok = (() => { 
                                                                                                        const base = outputs[0];
                                                                                                        for (let i = 1; i < outputs.length; i++) {
                                                                                                            if (outputs[i] !== base) return false;
                                                                                                        }
                                                                                                        return true;
                                                                                                     })();
                                                                                                if (!parity_ok) {
                                                                                                                                            console.log("   ❌ Parity Mismatch!");
                                                                                                                                            console.log("      JS Output: " + outputs, [0]);
                                                                                                                                            console.log("      Py Output: " + outputs, [1]);
                                                                                                                                            return false;
                                                                                                } else {
                                                                                                                                                console.log("   ✅ Parity OK");
                                                                                                }
                                                }
                                                return true;    },
    validate_execution(file, target) {
                                                let ext = ".js";
                                                let run_cmd = "node";
                                                    if (target === "python") {
                                                                                                        ext = ".py";
                                                                                                        run_cmd = "python";
                                                    }
                                                    let executable = OmniTester.EXAMPLES_DIR + "/" + file + "_out" + ext;
                                                    let command = run_cmd + " " + executable;
                                                    let result = (() => { 
                                                                const { execSync } = require('child_process');
                                                                const fs = require('fs');
                                                                
                                                                if (!fs.existsSync(executable)) return "__ERROR__";
                                                    
                                                                try {
                                                                    const out = execSync(command, { timeout: 5000, encoding: 'utf8' });
                                                                    return out.trim();
                                                                } catch(e) {
                                                                    console.log("      ❌ Runtime Error: " + e.message);
                                                                    return "__ERROR__";
                                                                }
                                                             })();
                                                    return result;    },
    generate_report(results, bugs) {
                                                    console.log("=========================================");
                                                    console.log("📊 RELATÓRIO FINAL DE ENGENHARIA");
                                                    console.log("   Bugs Encontrados: " + bugs);
                                                    let status_msg = "⚠️ REQUER MANUTENÇÃO";
                                                        if (bugs === 0) {
                                                                                                                status_msg = "✅ SISTEMA SOBERANO";
                                                        }
                                                        console.log("   Status: " + status_msg);
                                                        console.log("=========================================");    },

};

function main() {
                                                        OmniTester.run_full_suite();
}

if (typeof main === 'function') { main(); }
