// Generated by Omni Compiler
'use strict';


function print(msg) {
console.log(msg);

}

// Capsule: OmniTester
const OmniTester = {};

OmniTester.EXAMPLES_DIR = "./examples";
OmniTester.TARGETS = ["js", "python"];
OmniTester.run_full_suite = function() {
    print("🚀 Iniciando Suite de Testes Global do Omni...");
    let results = [];
    let total_bugs = 0;
    let files = OmniTester.scan_files();
    for (const file of files) {
    print("-----------------------------------------");
    print("🧪 Testando: " + file);
    let success = OmniTester.test_metamorphosis(file, OmniTester.TARGETS);
    if (success === false) {
    total_bugs = total_bugs + 1;
}

}

    OmniTester.generate_report(results, total_bugs);
}
;
OmniTester.test_metamorphosis = function(file, targets) {
    let outputs = [];
    let compile_errors = 0;
    let runtime_errors = 0;
    for (const target of targets) {
    print("   -> Target: " + target);
    let ext_out = ".js";
    if (target === "python") {
    ext_out = ".py";
}

    let cmd = OmniTester.get_compiler_cmd();
    cmd = cmd + " ";
    cmd = cmd + OmniTester.EXAMPLES_DIR;
    cmd = cmd + "/" + file + " ";
    cmd = cmd + OmniTester.EXAMPLES_DIR + "/" + file + "_out" + ext_out;
    cmd = cmd + " --target " + target;
    let compile_ok = OmniTester.exec_cmd(cmd);
    if (compile_ok === false) {
    compile_errors = compile_errors + 1;
    continue;
}

    let out_val = OmniTester.validate_execution(file, target);
    if (out_val === "__ERROR__") {
    runtime_errors = runtime_errors + 1;
}
 else {
    outputs.push(out_val);
}

}

    if (compile_errors > 0 || runtime_errors > 0) {
    return false;
}

    if (outputs.length > 1) {
    let base = outputs[0];
    let parity_ok = true;
    parity_ok = OmniTester.check_parity(outputs);
    if (parity_ok === false) {
    print("   ❌ Parity Mismatch!");
    print("      JS Output: " + outputs[0]);
    print("      Py Output: " + outputs[1]);
    return false;
}
 else {
    print("   ✅ Parity OK");
}

}

    return true;
}
;
OmniTester.validate_execution = function(file, target) {
    let ext = ".js";
    let run_cmd = "node";
    if (target === "python") {
    ext = ".py";
    run_cmd = "python";
}

    let executable = OmniTester.EXAMPLES_DIR + "/" + file + "_out" + ext;
    let command = run_cmd + " " + executable;
    let result = OmniTester.exec_runtime_cmd(command, executable);
    return result;
}
;
OmniTester.generate_report = function(results, bugs) {
    print("=========================================");
    print("📊 RELATÓRIO FINAL DE ENGENHARIA");
    print("   Bugs Encontrados: " + bugs);
    let status_msg = "⚠️ REQUER MANUTENÇÃO";
    if (bugs === 0) {
    status_msg = "✅ SISTEMA SOBERANO";
}

    print("   Status: " + status_msg);
    print("=========================================");
}
;
OmniTester.scan_files = function() {
const fs = require('fs');
            const path = require('path');
            const root = OmniTester.EXAMPLES_DIR;
            let all_files = [];
            
            const entries = fs.readdirSync(root, { withFileTypes: true });
            
            for (const entry of entries) {
                if (entry.isDirectory()) {
                    const dirPath = path.join(root, entry.name);
                    const subFiles = fs.readdirSync(dirPath).filter(f => f.endsWith('.omni'));
                    for (const sub of subFiles) {
                         all_files.push(entry.name + "/" + sub);
                    }
                } else if (entry.name.endsWith('.omni')) {
                    all_files.push(entry.name);
                }
            }
            return all_files;
}
;
OmniTester.get_compiler_cmd = function() {
return process.env.OMNI_COMPILER || ".\\omni.bat";
}
;
OmniTester.exec_cmd = function(cmd) {
const { execSync } = require('child_process');
            try { 
                execSync(cmd, { stdio: 'pipe' }); 
                return true; 
            } catch(e) { 
                console.log("      ❌ Compile Error: " + e.message);
                return false; 
            }
}
;
OmniTester.check_parity = function(outputs) {
const base = outputs[0];
            for (let i = 1; i < outputs.length; i++) {
                if (outputs[i] !== base) return false;
            }
            return true;
}
;
OmniTester.exec_runtime_cmd = function(command, executable) {
const { execSync } = require('child_process');
            const fs = require('fs');
            
            if (!fs.existsSync(executable)) return "__ERROR__";

            try {
                const out = execSync(command, { timeout: 5000, encoding: 'utf8' });
                return out.trim();
            } catch(e) {
                console.log("      ❌ Runtime Error: " + e.message);
                return "__ERROR__";
            }
}
;


function main() {
    OmniTester.run_full_suite();
}


// Entry Point
if (require.main === module) {
    main();
}
