// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
        print_opt(msg, true);
}
function to_string(n) {
            let result = "";
             result = String(n); 

            return result;
}
function to_string_f(n) {
                let result = "";
                 result = String(n); 

                return result;
}
function to_string_b(b) {
                    let result = "";
                     result = b ? 'true' : 'false'; 

                    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/regex.omni =====
function Regex_replace(text, pattern, replacement) {
    let result = "";
    
            // Assume global replacement
            const re = new RegExp(pattern, 'g');
            result = text.replace(re, replacement);
        

    return result;
}
function Regex_count(pattern, text) {
        let count = 0;
        
                const re = new RegExp(pattern, 'g');
                const matches = text.match(re);
                count = matches ? matches.length : 0;
            

        return count;
}
// ===== END: std/regex.omni =====

function count_functions(source) {
    return Regex_count("fn\\\\s+\\\\w+", source);
}
function count_structs(source) {
        return Regex_count("struct\\\\s+\\\\w+", source);
}
function main() {
            console.log("╔══════════════════════════════════════╗");
            console.log("║   OMNI - Self Scan                   ║");
            console.log("╚══════════════════════════════════════╝");
            console.log("");
            let sample = "fn main() {} fn helper() {} struct User {} struct Task {}";
            let fn_count = count_functions(sample);
            let struct_count = count_structs(sample);
            console.log("Sample code analysis:");
            console.log("  Functions: " + String(fn_count));
            console.log("  Structs: " + String(struct_count));
            console.log("");
            console.log("✓ Self scan example completed!");
}

module.exports = { count_functions, count_structs, main };

if (typeof main === 'function') { main(); }
