// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function count_functions(source) {{
        let count = 0;
        
                const matches = source.match(/fn\s+\w+/g);
                count = matches ? matches.length : 0;
            

        return count;
}}
function count_structs(source) {{
            let count = 0;
            
                    const matches = source.match(/struct\s+\w+/g);
                    count = matches ? matches.length : 0;
                

            return count;
}}
function main() {{
                print("╔══════════════════════════════════════╗");
                print("║   OMNI - Self Scan                   ║");
                print("╚══════════════════════════════════════╝");
                print("");
                let sample = "fn main() {} fn helper() {} struct User {} struct Task {}";
                let fn_count = count_functions(sample);
                let struct_count = count_structs(sample);
                print("Sample code analysis:");
                print("  Functions: " + fn_count);
                print("  Structs: " + struct_count);
                print("");
                print("✓ Self scan example completed!");
}}

if (typeof main === 'function') main();
