// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function sha256_hash(input) {{
        let result = "";
        
                const crypto = require('crypto');
                result = crypto.createHash('sha256').update(input).digest('hex');
            

        return result;
}}
function md5_hash(input) {{
            let result = "";
            
                    const crypto = require('crypto');
                    result = crypto.createHash('md5').update(input).digest('hex');
                

            return result;
}}
function main() {{
                print("╔══════════════════════════════════════╗");
                print("║   OMNI - Secure Hasher               ║");
                print("╚══════════════════════════════════════╝");
                print("");
                let input = "Hello, Omni!";
                print("Input: " + input);
                print("");
                print("1. SHA-256:");
                let sha = sha256_hash(input);
                print("   " + sha);
                print("");
                print("2. MD5:");
                let md = md5_hash(input);
                print("   " + md);
                print("");
                print("✓ Crypto example completed!");
}}

if (typeof main === 'function') main();
