// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
        print_opt(msg, true);
}
function to_string(n) {
            let result = "";
             result = String(n); 

            return result;
}
function to_string_f(n) {
                let result = "";
                 result = String(n); 

                return result;
}
function to_string_b(b) {
                    let result = "";
                     result = b ? 'true' : 'false'; 

                    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/crypto.omni =====
function sha256(input) {
    let result = "";
    
            if (typeof require !== 'undefined') {
                const crypto = require('crypto');
                result = crypto.createHash('sha256').update(input).digest('hex');
            } else {
                // Browser fallback (async in reality, but for synch example we might need a lib or simple implementation)
                // For now, simple mock or error in browser if no crypto lib loaded
                // But we can check for SubtleCrypto? That's async. 
                // We'll stick to Node.js for 'crypto' module or simple string hash for browser demo.
                let h = 0x811c9dc5;
                for (let i = 0; i < input.length; i++) {
                    h ^= input.charCodeAt(i);
                    h = Math.imul(h, 0x01000193);
                }
                result = (h >>> 0).toString(16);
            }
        

    return result;
}
function md5(input) {
        let result = "";
        
                if (typeof require !== 'undefined') {
                    const crypto = require('crypto');
                    result = crypto.createHash('md5').update(input).digest('hex');
                } else {
                     // Simple djb2 for non-node fallback mock
                    let h = 5381;
                    for (let i = 0; i < input.length; i++) {
                        h = (h * 33) ^ input.charCodeAt(i);
                    }
                    result = (h >>> 0).toString(16);
                }
            

        return result;
}
// ===== END: std/crypto.omni =====

function main() {
    console.log("╔══════════════════════════════════════╗");
    console.log("║   OMNI - Secure Hasher               ║");
    console.log("╚══════════════════════════════════════╝");
    console.log("");
    let input = "Hello, Omni!";
    console.log("Input: " + input);
    console.log("");
    console.log("1. SHA-256:");
    let sha = sha256(input);
    console.log("   " + sha);
    console.log("");
    console.log("2. MD5:");
    let md = md5(input);
    console.log("   " + md);
    console.log("");
    console.log("✓ Crypto example completed!");
}

module.exports = { main };

if (typeof main === 'function') { main(); }
