// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print(msg) {{
    
            console.log(msg);
            if (typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}}
function to_string(n) {{
        let result = "";
         result = String(n); 

        return result;
}}
function to_string_f(n) {{
            let result = "";
             result = String(n); 

            return result;
}}
function to_string_b(b) {{
                let result = "";
                 result = b ? 'true' : 'false'; 

                return result;
}}
// ===== END: std/core.omni =====

function greet(name) {{
    return "Hello, " + name + "! Welcome to Omni.";
}}
function add(a, b) {{
        return a + b;
}}
function multiply(a, b) {{
            return a * b;
}}
function main() {{
                print("╔══════════════════════════════════════╗");
                print("║   OMNI - Hello Universal             ║");
                print("╚══════════════════════════════════════╝");
                print("");
                print("1. Simple Output:");
                print("   Hello, World!");
                print("");
                print("2. Arithmetic:");
                let sum = add(42, 58);
                let product = multiply(7, 6);
                print("   42 + 58 = " + to_string(sum));
                print("   7 * 6 = " + to_string(product));
                print("");
                print("3. Greeting:");
                print("   " + greet("Developer"));
                print("");
                print("✓ Pure Omni - works everywhere!");
}}

if (typeof main === 'function') main();
