# Generated by Omni Compiler

# ===== INLINE: std/core.omni =====
def print_opt(msg, show_ui):

    
    import sys
    # Console output
    sys.stdout.write(str(msg) + '\n')
    sys.stdout.flush()
    
    # UI Output (Tkinter)
    if show_ui:
        try:
            import tkinter as tk
            if not hasattr(sys, 'omni_root') or sys.omni_root is None:
                sys.omni_root = tk.Tk()
                sys.omni_root.title("Omni App Logs")
                sys.omni_root.geometry("600x400")
                sys.omni_root.configure(bg="#1a1a2e")
                
                sys.omni_text = tk.Text(sys.omni_root, bg="#1a1a2e", fg="#0f0", font=("Consolas", 10))
                sys.omni_text.pack(expand=True, fill='both')
                
                # Handle close
                def on_close():
                    sys.omni_root.destroy()
                    sys.omni_root = None
                sys.omni_root.protocol("WM_DELETE_WINDOW", on_close)
    
            if sys.omni_root:
                sys.omni_text.insert(tk.END, str(msg) + "\n")
                sys.omni_text.see(tk.END)
                sys.omni_root.update()
        except Exception as e:
            sys.stderr.write(f"UI Error: {e}\n")
        
def print(msg):
    print_opt(msg, True);
def to_string(n):
    result = ""

    
    result = str(n)
        
    return result
def to_string_f(n):
    result = ""

    
    result = str(n)
        
    return result
def to_string_b(b):
    result = ""

    
    result = 'true' if b else 'false'
        
    return result
# ===== END: std/core.omni =====

def greet(name):
    return "Hello, " + name + "! Welcome to Omni."
def add(a, b):
    return a + b
def multiply(a, b):
    return a * b
def main():
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - Hello Universal             ║");
    print("╚══════════════════════════════════════╝");
    print("");
    print("1. Simple Output:");
    print("   Hello, World!");
    print("");
    print("2. Arithmetic:");
    sum = add(42, 58)
    product = multiply(7, 6)
    print("   42 + 58 = " + to_string(sum));
    print("   7 * 6 = " + to_string(product));
    print("");
    print("3. Greeting:");
    print("   " + greet("Developer"));
    print("");
    print("✓ Pure Omni - works everywhere!");

if __name__ == '__main__':
    main()
    import sys
    if hasattr(sys, 'omni_root') and sys.omni_root:
        print('ℹ App running. Close window to exit.')
        try:
            sys.omni_root.mainloop()
        except KeyboardInterrupt:
            pass
