// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
    print_opt(msg, true);
}
function to_string(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_f(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_b(b) {
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/regex.omni =====
function Regex_replace(text, pattern, replacement) {
    let result = "";
    
            // Assume global replacement
            const re = new RegExp(pattern, 'g');
            result = text.replace(re, replacement);
        

    return result;
}
function Regex_count(pattern, text) {
    let count = 0;
    
            const re = new RegExp(pattern, 'g');
            const matches = text.match(re);
            count = matches ? matches.length : 0;
        

    return count;
}
// ===== END: std/regex.omni =====

function convert_php_line(line) {
    let result = "// Converted: ";
    let step1 = Regex_replace(line, "\\$", "let ");
    let step2 = Regex_replace(step1, "->", ".");
    result = result + step2;
    return result;
}
function main() {
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - Legacy Converter Demo       ║");
    print("╚══════════════════════════════════════╝");
    print("");
    print("1. Original PHP Code:");
    print("   $user = new User();");
    print("   $user->name = 'Alice';");
    print("");
    print("2. Converted to Omni-style:");
    print(convert_php_line("$user = new User();"));
    print(convert_php_line("$user->name = 'Alice';"));
    print("");
    print("3. Conversion Features:");
    print("   - Variable prefix $ removed");
    print("   - Arrow -> becomes dot .");
    print("   - New regex lib used (std/regex.omni)");
    print("");
    print("✓ Legacy converter example completed!");
}

if (typeof main === 'function') main();
