// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
        print_opt(msg, true);
}
function to_string(n) {
            let result = "";
             result = String(n); 

            return result;
}
function to_string_f(n) {
                let result = "";
                 result = String(n); 

                return result;
}
function to_string_b(b) {
                    let result = "";
                     result = b ? 'true' : 'false'; 

                    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/regex.omni =====
function Regex_replace(text, pattern, replacement) {
    let result = "";
    
            // Assume global replacement
            const re = new RegExp(pattern, 'g');
            result = text.replace(re, replacement);
        

    return result;
}
function Regex_count(pattern, text) {
        let count = 0;
        
                const re = new RegExp(pattern, 'g');
                const matches = text.match(re);
                count = matches ? matches.length : 0;
            

        return count;
}
// ===== END: std/regex.omni =====

function convert_php_line(line) {
    let result = "// Converted: ";
    let step1 = Regex_replace(line, "\\\\$", "let ");
    let step2 = Regex_replace(step1, "->", ".");
    result = result + step2;
    return result;
}
function main() {
        console.log("╔══════════════════════════════════════╗");
        console.log("║   OMNI - Legacy Converter Demo       ║");
        console.log("╚══════════════════════════════════════╝");
        console.log("");
        console.log("1. Original PHP Code:");
        console.log("   $user = new User();");
        console.log("   $user->name = 'Alice';");
        console.log("");
        console.log("2. Converted to Omni-style:");
        console.log(convert_php_line("$user = new User();"));
        console.log(convert_php_line("$user->name = 'Alice';"));
        console.log("");
        console.log("3. Conversion Features:");
        console.log("   - Variable prefix $ removed");
        console.log("   - Arrow -> becomes dot .");
        console.log("   - New regex lib used (std/regex.omni)");
        console.log("");
        console.log("✓ Legacy converter example completed!");
}

module.exports = { convert_php_line, main };

if (typeof main === 'function') { main(); }
