// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function convert_php_line(line) {{
        let result = "// Converted: ";
        
                result = result + line.replace('$', 'let ').replace('->', '.');
            

        return result;
}}
function main() {{
            print("╔══════════════════════════════════════╗");
            print("║   OMNI - Legacy Converter Demo       ║");
            print("╚══════════════════════════════════════╝");
            print("");
            print("1. Original PHP Code:");
            print("   $user = new User();");
            print("   $user->name = 'Alice';");
            print("");
            print("2. Converted to Omni-style:");
            print("   let user = User {};");
            print("   user.name = 'Alice';");
            print("");
            print("3. Conversion Features:");
            print("   - Variable prefix $ removed");
            print("   - Arrow -> becomes dot .");
            print("   - New syntax adapted");
            print("");
            print("✓ Legacy converter example completed!");
}}

if (typeof main === 'function') main();
