// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 
}}
class Payment {{
    constructor(data = {}) {
        this.id = data.id;
        this.amount = data.amount;
        this.status = data.status;
        this.timestamp = data.timestamp;
    }

}}
function create_ui() {{
        
                document.body.innerHTML = `
                    <div style="padding: 40px; font-family: sans-serif; max-width: 500px; margin: 0 auto;">
                        <h1>💳 Payment Flow</h1>
                        <div style="background: #f5f5f5; padding: 20px; border-radius: 8px;">
                            <label>Amount ($):</label>
                            <input id="amount" type="number" value="10.00" step="0.01" style="width: 100%; padding: 10px; margin: 10px 0;">
                            <button onclick="processPayment()" style="width: 100%; padding: 15px; background: #4CAF50; color: white; border: none; cursor: pointer;">
                                Process Payment
                            </button>
                        </div>
                        <div id="log" style="margin-top: 20px; padding: 10px; background: #333; color: #0f0; font-family: monospace; border-radius: 4px;"></div>
                    </div>
                `;
                
                window.processPayment = function() {
                    const amount = document.getElementById('amount').value;
                    const log = document.getElementById('log');
                    const id = 'PAY_' + Date.now();
                    
                    log.innerHTML += '[' + new Date().toISOString() + '] Processing $' + amount + '...<br>';
                    
                    setTimeout(() => {
                        log.innerHTML += '[' + new Date().toISOString() + '] Payment ' + id + ' APPROVED<br>';
                    }, 1000);
                };
            
}}
function main() {{
            print("Starting Payment Flow...");
            create_ui();
}}
