// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function build_select(table, fields) {{
        return "SELECT " + fields + " FROM " + table;
}}
function build_where(query, condition) {{
            return query + " WHERE " + condition;
}}
function build_order(query, field) {{
                return query + " ORDER BY " + field;
}}
function main() {{
                    print("╔══════════════════════════════════════╗");
                    print("║   OMNI - SQL Query Builder           ║");
                    print("╚══════════════════════════════════════╝");
                    print("");
                    print("Building a SQL query:");
                    print("");
                    let q1 = build_select("users", "*");
                    print("1. " + q1);
                    let q2 = build_where(q1, "active = true");
                    print("2. " + q2);
                    let q3 = build_order(q2, "created_at DESC");
                    print("3. " + q3);
                    print("");
                    print("Final Query:");
                    print("   " + q3);
                    print("");
                    print("✓ SQL Query Builder example completed!");
}}

if (typeof main === 'function') main();
