// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
    print_opt(msg, true);
}
function to_string(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_f(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_b(b) {
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/sql.omni =====
class Query {
    constructor(data = {}) {
        this.table = data.table;
        this.fields = data.fields;
        this.where_clause = data.where_clause;
        this.order_clause = data.order_clause;
        this.limit = data.limit;
    }

}
function Query_select(table) {
    return new Query({ table: table, fields: "*", where_clause: "", order_clause: "", limit: 0 });
}
function Query_fields(q, fields) {
    q.fields = fields;
    return q;
}
function Query_where(q, condition) {
    if (q.where_clause === "") {
            q.where_clause = condition;
    } else {
            q.where_clause = q.where_clause + " AND " + condition;
    }
    return q;
}
function Query_order_by(q, field) {
    q.order_clause = field;
    return q;
}
function Query_limit(q, limit) {
    q.limit = limit;
    return q;
}
function Query_to_string(q) {
    let sql = "SELECT " + q.fields + " FROM " + q.table;
    if (q.where_clause !== "") {
            sql = sql + " WHERE " + q.where_clause;
    }
    if (q.order_clause !== "") {
            sql = sql + " ORDER BY " + q.order_clause;
    }
    if (q.limit > 0) {
            sql = sql + " LIMIT " + q.limit;
    }
    return sql;
}
// ===== END: std/sql.omni =====

function main() {
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - SQL Query Builder           ║");
    print("╚══════════════════════════════════════╝");
    print("");
    print("Building a SQL query:");
    print("");
    let q = Query_select("users");
    print("1. " + Query_to_string(q));
    q = Query_where(q, "active = true");
    q = Query_where(q, "age >= 18");
    print("2. " + Query_to_string(q));
    q = Query_order_by(q, "created_at DESC");
    q = Query_limit(q, 50);
    print("3. " + Query_to_string(q));
    print("");
    print("Final Query:");
    print("   " + Query_to_string(q));
    print("");
    print("✓ SQL Query Builder example completed!");
}

if (typeof main === 'function') main();
