// Generated by Omni Compiler
'use strict';

function print(msg) {{
     console.log(msg); 

}}
function read_file_demo(path) {{
        let content = "";
        
                const fs = require('fs');
                try {
                    content = fs.readFileSync(path, 'utf8');
                } catch (e) {
                    content = "[Error reading file]";
                }
            

        return content;
}}
function write_file_demo(path, content) {{
            let success = false;
            
                    const fs = require('fs');
                    try {
                        fs.writeFileSync(path, content);
                        success = true;
                    } catch (e) {}
                

            return success;
}}
function main() {{
                print("╔══════════════════════════════════════╗");
                print("║   OMNI - File System Master          ║");
                print("╚══════════════════════════════════════╝");
                print("");
                let test_file = "omni_test_output.txt";
                let test_content = "Hello from Omni!";
                print("1. Writing File:");
                let wrote = write_file_demo(test_file, test_content);
                    if (wrote) {{
                                        print("   Written to: " + test_file);
                    }}
                    print("");
                    print("2. Reading File:");
                    let read_content = read_file_demo(test_file);
                    print("   Content: " + read_content);
                    print("");
                    print("✓ File system example completed!");
}}

if (typeof main === 'function') main();
