// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
    print_opt(msg, true);
}
function to_string(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_f(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_b(b) {
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/io.omni =====
function read_file(path) {
    let content = "";
    
            const fs = require("fs");
            try {
                content = fs.readFileSync(path, "utf8");
            } catch (e) {
                console.error("Error reading file " + path + ": " + e.message);
            }
        

    return content;
}
function write_file(path, content) {
    let success = false;
    
            const fs = require("fs");
            try {
                fs.writeFileSync(path, content);
                success = true;
            } catch (e) {
                console.error("Error writing file " + path + ": " + e.message);
            }
        

    return success;
}
function file_exists(path) {
    let exists = false;
    
            const fs = require("fs");
            exists = fs.existsSync(path);
        

    return exists;
}
function read_dir(path) {
    let files = 0;
    
            const fs = require("fs");
            try {
                files = fs.readdirSync(path);
            } catch (e) {}
        

    return files;
}
// ===== END: std/io.omni =====

function main() {
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - File System Master          ║");
    print("╚══════════════════════════════════════╝");
    print("");
    let test_file = "omni_test_output.txt";
    let test_content = "Hello from Omni!";
    print("1. Writing File:");
    let wrote = write_file(test_file, test_content);
    if (wrote) {
            print("   Written to: " + test_file);
    }
    print("");
    print("2. Reading File:");
    let read_content = read_file(test_file);
    print("   Content: " + read_content);
    print("");
    print("✓ File system example completed!");
}

if (typeof main === 'function') main();
