// Generated by Omni Compiler
'use strict';

// ===== INLINE: std/core.omni =====
function print_opt(msg, show_ui) {
    
            console.log(msg);
            if (show_ui && typeof document !== 'undefined') {
                let c = document.getElementById('out');
                if (!c) {
                    c = document.createElement('pre');
                    c.id = 'out';
                    c.style.cssText = 'padding:20px;font-family:monospace;font-size:14px;background:#1a1a2e;color:#0f0;max-width:600px;margin:40px auto;border-radius:8px;';
                    document.body.style.background = '#0f0f23';
                    document.body.appendChild(c);
                }
                c.textContent += msg + '\n';
            }
        

}
function print(msg) {
    print_opt(msg, true);
}
function to_string(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_f(n) {
    let result = "";
     result = String(n); 

    return result;
}
function to_string_b(b) {
    let result = "";
     result = b ? 'true' : 'false'; 

    return result;
}
// ===== END: std/core.omni =====

// ===== INLINE: std/time.omni =====
function Time_now_ms() {
    let t = 0;
    
            t = Date.now();
        

    return t;
}
function Time_schedule(delay_ms, callback) {
    
            setTimeout(callback, delay_ms);
        

}
// ===== END: std/time.omni =====

let tasks_completed = 0;
let start_time = 0;
function task_done() {
    ;
    print("   [Worker] Task finished!");
    if (tasks_completed === 4) {
            let end_time = Time_now_ms();
            let duration = end_time - start_time;
            print("");
            print("3. Worker Stats:");
            print("   Tasks completed: " + to_string(tasks_completed));
            print("   Total time: " + to_string(duration) + "ms");
            print("");
            print("✓ Background worker example completed!");
    }
}
function process_task(id, name, delay) {
    print("   [Task " + to_string(id) + "] Scheduled: " + name + " (" + to_string(delay) + "ms)");
    Time_schedule(delay, task_done);
}
function main() {
    print("╔══════════════════════════════════════╗");
    print("║   OMNI - Background Worker           ║");
    print("╚══════════════════════════════════════╝");
    print("");
    ;
    print("1. Creating Task Queue:");
    print("   Queue initialized");
    print("");
    print("2. Scheduling Tasks:");
    process_task(1, "Parse data", 500);
    process_task(2, "Transform records", 1000);
    process_task(3, "Save to database", 1500);
    process_task(4, "Send notification", 2000);
    print("");
    print("   (Main thread continues while workers run...)");
}

if (typeof main === 'function') main();
